/*
Generated by LwipMibCompiler
*/

#ifndef LLDP_EXT_ODVA_V01_H
#define LLDP_EXT_ODVA_V01_H LLDP_EXT_ODVA_V01_H

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "lwip/apps/snmp_core.h"

extern const struct snmp_mib lldpxodvamib;

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* LWIP_SNMP */
#endif /* LLDP_EXT_ODVA_V01_H */
