/*
Generated by LwipMibCompiler
*/

#ifndef LLDP_MIB_H
#define LLDP_MIB_H LLDP_MIB_H

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP && LWIP_LLDP

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "lwip/apps/snmp_core.h"

extern const struct snmp_mib lldpmib;

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* LWIP_SNMP && LWIP_LLDP */
#endif /* LLDP_MIB_H */
