/*
Generated by LwipMibCompiler
*/

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP

#include "lldp-ext-odva-v01.h"
#include "lwip/apps/snmp.h"
#include "lwip/apps/snmp_core.h"
#include "lwip/apps/snmp_scalar.h"
#include "lwip/apps/snmp_table.h"

#include "lwip/netif.h"
#include "lwip_lldp_mib.h"
#include "lwip_lldp_def.h"
#include "lwip/ip4_addr.h"

#include "cipidentity.h"

#if LWIP_LLDP_SUPPORT_CIP_TLV

/* --- lldpXOdvaLocalData 1.0.8802.1.1.2.1.5.8556.1.2 ----------------------------------------------------- */
static snmp_err_t lldpxodvaloctable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance);
static snmp_err_t lldpxodvaloctable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance);
static s16_t lldpxodvaloctable_get_value(struct snmp_node_instance *cell_instance, void *value);
static const struct snmp_table_col_def lldpxodvaloctable_columns[] = {
  {1, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaLocCIPIdentVendorID */ 
  {2, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaLocCIPIdentDeviceType */ 
  {3, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaLocCIPIdentProductCode */ 
  {4, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaLocCIPIdentMajorRev */ 
  {5, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaLocCIPIdentMinorRev */ 
  {6, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaLocCIPIdentSerialNumber */ 
  {7, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaLocCIPMacAddress */ 
  {8, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaLocCIPInterfaceLabel */ 
  {9, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaLocCIPPositionID */ 
  {10, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaLocCIPPHYMode */ 
  {11, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaLocCIPPLCAPHYNodeID */ 
};
static const struct snmp_table_node lldpxodvaloctable = SNMP_TABLE_CREATE(1, lldpxodvaloctable_columns, lldpxodvaloctable_get_instance, lldpxodvaloctable_get_next_instance, lldpxodvaloctable_get_value, NULL, NULL);

static const struct snmp_node *const lldpxodvalocaldata_subnodes[] = {
  &lldpxodvaloctable.node.node
};
static const struct snmp_tree_node lldpxodvalocaldata_treenode = SNMP_CREATE_TREE_NODE(2, lldpxodvalocaldata_subnodes);

/* --- lldpXOdvaRemoteData 1.0.8802.1.1.2.1.5.8556.1.3 ----------------------------------------------------- */
static snmp_err_t lldpxodvaremtable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance);
static snmp_err_t lldpxodvaremtable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance);
static s16_t lldpxodvaremtable_get_value(struct snmp_node_instance *cell_instance, void *value);
static const struct snmp_table_col_def lldpxodvaremtable_columns[] = {
  {1, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaRemCIPIdentVendorID */ 
  {2, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaRemCIPIdentDeviceType */ 
  {3, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaRemCIPIdentProductCode */ 
  {4, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaRemCIPIdentMajorRev */ 
  {5, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaRemCIPIdentMinorRev */ 
  {6, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaRemCIPIdentSerialNumber */ 
  {7, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaRemCIPMacAddress */ 
  {8, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaRemCIPInterfaceLabel */ 
  {9, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaRemCIPPositionID */ 
  {10, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaRemCIPPHYMode */ 
  {11, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpXOdvaRemCIPPLCAPHYNodeID */ 
};
static const struct snmp_table_node lldpxodvaremtable = SNMP_TABLE_CREATE(1, lldpxodvaremtable_columns, lldpxodvaremtable_get_instance, lldpxodvaremtable_get_next_instance, lldpxodvaremtable_get_value, NULL, NULL);

static const struct snmp_node *const lldpxodvaremotedata_subnodes[] = {
  &lldpxodvaremtable.node.node
};
static const struct snmp_tree_node lldpxodvaremotedata_treenode = SNMP_CREATE_TREE_NODE(3, lldpxodvaremotedata_subnodes);

/* --- lldpXOdvaObjects 1.0.8802.1.1.2.1.5.8556.1 ----------------------------------------------------- */
static const struct snmp_node *const lldpxodvaobjects_subnodes[] = {
  &lldpxodvalocaldata_treenode.node,
  &lldpxodvaremotedata_treenode.node
};
static const struct snmp_tree_node lldpxodvaobjects_treenode = SNMP_CREATE_TREE_NODE(1, lldpxodvaobjects_subnodes);

/* --- lldpXOdvaMIB  ----------------------------------------------------- */
static const struct snmp_node *const lldpxodvamib_subnodes[] = {
  &lldpxodvaobjects_treenode.node
};
static const struct snmp_tree_node lldpxodvamib_root = SNMP_CREATE_TREE_NODE(8556, lldpxodvamib_subnodes);
static const u32_t lldpxodvamib_base_oid[] = {1,0,8802,1,1,2,1,5,8556};
const struct snmp_mib lldpxodvamib = {lldpxodvamib_base_oid, LWIP_ARRAYSIZE(lldpxodvamib_base_oid), &lldpxodvamib_root.node};

static LWIP_LLDP_AGENT_VARIABLES glldp_agent = {0};

/*
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
LWIP MIB generator - preserved section begin
Code below is preserved on regeneration. Remove these comment lines to regenerate code.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
*/

/* --- lldpXOdvaLocalData 1.0.8802.1.1.2.1.5.8556.1.2 ----------------------------------------------------- */

/* list of allowed value ranges for incoming OID */
static const struct snmp_oid_range lldpxodvaloc_Table_oid_ranges[] = {
  { 1, 0x1000 } /* lldpLocPortNum */
};

static snmp_err_t lldpxodvaloctable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance)
{
	/*
	 The instance OID of this table consists of following (index) column(s):
	 lldpLocPortNum (Integer, OID length = 1)
	 */
	u32_t lldp_port_id;
	struct netif *netif;

	/* Treat unused parameters */
	LWIP_UNUSED_ARG(column);
	LWIP_UNUSED_ARG(cell_instance);

   /* check if incoming OID length and if values are in plausible range */
   if (!snmp_oid_in_range(row_oid, row_oid_len, lldpxodvaloc_Table_oid_ranges, LWIP_ARRAYSIZE(lldpxodvaloc_Table_oid_ranges))) {
     return SNMP_ERR_NOSUCHINSTANCE;
   }

    /* get netif lldp port identifier from incoming OID */
	lldp_port_id = row_oid[0];

	/* find netif with index */
	NETIF_FOREACH(netif) {
		if (netif->lldp_port_id != 0) {
			if (netif->lldp_port_id == lldp_port_id) {
				/* store netif pointer for subsequent operations (get/test/set) */
				cell_instance->reference.ptr = netif;
				return SNMP_ERR_NOERROR;
			}
		}
	}

   /* not found */
   return SNMP_ERR_NOSUCHINSTANCE;
}
static snmp_err_t lldpxodvaloctable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance)
{
   /*
   The instance OID of this table consists of following (index) column(s):
    lldpLocPortNum (Integer, OID length = 1)
   */
	struct netif *netif;
	struct snmp_next_oid_state state;
	u32_t result_temp[LWIP_ARRAYSIZE(lldpxodvaloc_Table_oid_ranges)];

   /* Treat unused parameters */
   LWIP_UNUSED_ARG(column);

   /* init struct to search next oid */
   snmp_next_oid_init(&state, row_oid->id, row_oid->len, result_temp, LWIP_ARRAYSIZE(lldpxodvaloc_Table_oid_ranges));

   /* iterate over all possible OIDs to find the next one */
   NETIF_FOREACH(netif) {
     if (netif->lldp_port_id != 0) {
       u32_t test_oid[LWIP_ARRAYSIZE(lldpxodvaloc_Table_oid_ranges)];
       test_oid[0] = netif->lldp_port_id;

       /* check generated OID: is it a candidate for the next one? */
       snmp_next_oid_check(&state, test_oid, LWIP_ARRAYSIZE(lldpxodvaloc_Table_oid_ranges), netif);
     }
   }

   /* did we find a next one? */
   if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS) {
     snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
     /* store netif pointer for subsequent operations (get/test/set) */
     cell_instance->reference.ptr = /* (struct netif*) */state.reference;
     return SNMP_ERR_NOERROR;
   }

   /* not found */
   return SNMP_ERR_NOSUCHINSTANCE;
}
static s16_t lldpxodvaloctable_get_value(struct snmp_node_instance *cell_instance, void *value)
{
   struct netif *netif = (struct netif *)cell_instance->reference.ptr;
   s16_t value_len;

   memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
   if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
     LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
   }

   switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
   {
      case 1:
         {
            /* lldpXOdvaLocCIPIdentVendorID */
            u32_t *v = (u32_t *)value;
            value_len = sizeof(u32_t);
            *v = (s32_t) *glldp_agent.tx.local_system_mib.cip_vendor_id;
         }
         break;
      case 2:
         {
            /* lldpXOdvaLocCIPIdentDeviceType */
            u32_t *v = (u32_t *)value;
            value_len = sizeof(u32_t);
            *v = (s32_t) *glldp_agent.tx.local_system_mib.cip_device_type;
         }
         break;
      case 3:
         {
            /* lldpXOdvaLocCIPIdentProductCode */
            u32_t *v = (u32_t *)value;
            value_len = sizeof(u32_t);
            *v = (s32_t) *glldp_agent.tx.local_system_mib.cip_product_code;
         }
         break;
      case 4:
         {
            /* lldpXOdvaLocCIPIdentMajorRev */
            u32_t *v = (u32_t *)value;
            value_len = sizeof(u32_t);
            CipRevision revision = *glldp_agent.tx.local_system_mib.cip_revision;
            *v = (s32_t) revision.major_revision;
         }
         break;
      case 5:
         {
            /* lldpXOdvaLocCIPIdentMinorRev */
            u32_t *v = (u32_t *)value;
            value_len = sizeof(u32_t);
            CipRevision revision = *glldp_agent.tx.local_system_mib.cip_revision;
            *v = (s32_t) revision.minor_revision;
         }
         break;
      case 6:
         {
            /* lldpXOdvaLocCIPIdentSerialNumber */
            u32_t *v = (u32_t *)value;
            value_len = sizeof(u32_t);
            *v = (u32_t) *glldp_agent.tx.local_system_mib.cip_serial_number;
         }
         break;
      case 7:
         {
            /* lldpXOdvaLocCIPMacAddress */
             u8_t *v = (u8_t *)value;
            value_len = LWIP_LLDP_CIP_MAC_TLV_LEN;
            memcpy((void *)v, (void *)glldp_agent.tx.local_system_mib.cip_mac_address, (size_t)value_len);
         }
         break;
      case 8:
         {
            /* lldpXOdvaLocCIPInterfaceLabel */
             u8_t *v = (u8_t *)value;
            value_len = (s16_t) glldp_agent.tx.local_system_mib.cip_if_label_len;
            memcpy((void *)v, (void *)glldp_agent.tx.local_system_mib.cip_if_label, (size_t)value_len);
         }
         break;
      case 9:
         {
            /* lldpXOdvaLocCIPPositionID */
            u32_t *v = (u32_t *)value;

            /* TODO: put requested value to '*v' here */
            //value_len = sizeof(u32_t);
            value_len = 0;  //TODO local odva value
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 10:
         {
            /* lldpXOdvaLocCIPPHYMode */
            u32_t *v = (u32_t *)value;

            /* TODO: put requested value to '*v' here */
            //value_len = sizeof(u32_t);
            value_len = 0;  //TODO local odva value
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 11:
         {
            /* lldpXOdvaLocCIPPLCAPHYNodeID */
            u32_t *v = (u32_t *)value;

            /* TODO: put requested value to '*v' here */
            //value_len = sizeof(u32_t);
            value_len = 0;  //TODO local odva value
            LWIP_UNUSED_ARG(v);
         }
         break;
      default:
         {
            LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpxodvaloctable_get_value(): unknown id: %"S32_F"\n", SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id)));
            value_len = 0;
         }
         break;
   }
   return value_len;
}

/* --- lldpXOdvaRemoteData 1.0.8802.1.1.2.1.5.8556.1.3 ----------------------------------------------------- */

/* list of allowed value ranges for incoming OID */
static const struct snmp_oid_range lldxodvaprem_Table_oid_ranges[] = {
  { 0, 0xffffffff }, /* lldpRemTimeMark */
  { 1, 0x1000 },     /* lldpRemLocalPortNum */
  { 1, 0x7fffffff }, /* lldpRemIndex */
};

static snmp_err_t lldpxodvaremtable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance)
{
   struct netif *netif;
   u32_t TimeMark;
   u32_t lldp_port_id;
   u32_t RemIndex;
   u8_t byIndex;

   LWIP_UNUSED_ARG(column);
   LWIP_UNUSED_ARG(row_oid_len);

   /* get netif lldp port identifier from incoming OID */
   TimeMark = row_oid[0];
   lldp_port_id = row_oid[1];
   RemIndex = row_oid[2];

   NETIF_FOREACH(netif) {
     if (netif->lldp_port_id != 0) {
       if (netif->lldp_port_id == lldp_port_id) {
         memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
         if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
           LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
         }
         for (byIndex = 0; byIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS; byIndex++) {
           if (glldp_agent.rx.remote_system_mib_used[byIndex] == false) {
             continue;
           } else {
             if (glldp_agent.rx.rem_time_mark[byIndex] == TimeMark) {
               if ((u32_t)(byIndex + 1) == RemIndex) {
                   /* store netif pointer for subsequent operations (get/test/set) */
                   cell_instance->reference.ptr = netif;
                   return SNMP_ERR_NOERROR;
               }
             }
           }
         }
       }
     }
   }

   /* not found */
   return SNMP_ERR_NOSUCHINSTANCE;
}

static snmp_err_t lldpxodvaremtable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance)
{
   struct netif *netif;
   u8_t byIndex;
   struct snmp_next_oid_state state;
   u32_t result_temp[LWIP_ARRAYSIZE(lldxodvaprem_Table_oid_ranges)];

   LWIP_UNUSED_ARG(column);

   /* init struct to search next oid */
   snmp_next_oid_init(&state, row_oid->id, row_oid->len, result_temp, LWIP_ARRAYSIZE(lldxodvaprem_Table_oid_ranges));

   /* iterate over all possible OIDs to find the next one */
   NETIF_FOREACH(netif) {
     if (netif->lldp_port_id != 0) {
       memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
       if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
         LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
       }
       for (byIndex = 0; byIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS; byIndex++) {
         if (glldp_agent.rx.remote_system_mib_used[byIndex] == false) {
           continue;
         } else {
           u32_t test_oid[LWIP_ARRAYSIZE(lldxodvaprem_Table_oid_ranges)];

           test_oid[0] = glldp_agent.rx.rem_time_mark[byIndex];
           test_oid[1] = netif->lldp_port_id;
           test_oid[2] = (u32_t) byIndex + 1;

           /* check generated OID: is it a candidate for the next one? */
           snmp_next_oid_check(&state, test_oid, LWIP_ARRAYSIZE(lldxodvaprem_Table_oid_ranges), netif);
         }
       }
     }
   }

   /* did we find a next one? */
   if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS) {
     snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
     /* store netif pointer for subsequent operations (get/test/set) */
     cell_instance->reference.ptr = /* (struct netif*) */state.reference;
     return SNMP_ERR_NOERROR;
   }

   /* not found */
   return SNMP_ERR_NOSUCHINSTANCE;
}

static s16_t lldpxodvaremtable_get_value(struct snmp_node_instance *cell_instance, void *value)
{
struct netif *netif = (struct netif *)cell_instance->reference.ptr;
   s16_t value_len = 0;
   u32_t RemIndex;

   memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
   if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
     LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
   }

   switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
   {
      case 1:
         {
            /* lldpXOdvaRemCIPIdentVendorID */
            u32_t *v = (u32_t *)value;

            RemIndex = cell_instance->instance_oid.id[4] - 1;
            value_len = sizeof(u32_t);
            *v = (u32_t) glldp_agent.rx.remote_system_mib[RemIndex].cip_vendor_id;
         }
         break;
      case 2:
         {
            /* lldpXOdvaRemCIPIdentDeviceType */
            u32_t *v = (u32_t *)value;

            RemIndex = cell_instance->instance_oid.id[4] - 1;
            value_len = sizeof(u32_t);
            *v = (u32_t) glldp_agent.rx.remote_system_mib[RemIndex].cip_device_type;
         }
         break;
      case 3:
         {
            /* lldpXOdvaRemCIPIdentProductCode */
            u32_t *v = (u32_t *)value;

            RemIndex = cell_instance->instance_oid.id[4] - 1;
            value_len = sizeof(u32_t);
            *v = (u32_t) glldp_agent.rx.remote_system_mib[RemIndex].cip_product_code;
         }
         break;
      case 4:
         {
            /* lldpXOdvaRemCIPIdentMajorRev */
            u32_t *v = (u32_t *)value;

            RemIndex = cell_instance->instance_oid.id[4] - 1;
            value_len = sizeof(u32_t);
            *v = (u32_t) glldp_agent.rx.remote_system_mib[RemIndex].cip_revision.major_revision;
         }
         break;
      case 5:
         {
            /* lldpXOdvaRemCIPIdentMinorRev */
            u32_t *v = (u32_t *)value;

            RemIndex = cell_instance->instance_oid.id[4] - 1;
            value_len = sizeof(u32_t);
            *v = (u32_t) glldp_agent.rx.remote_system_mib[RemIndex].cip_revision.minor_revision;
         }
         break;
      case 6:
         {
            /* lldpXOdvaRemCIPIdentSerialNumber */
            u32_t *v = (u32_t *)value;

            RemIndex = cell_instance->instance_oid.id[4] - 1;
            value_len = sizeof(u32_t);
            *v = (u32_t) glldp_agent.rx.remote_system_mib[RemIndex].cip_serial_number;
         }
         break;
      case 7:
         {
            /* lldpXOdvaRemCIPMacAddress */
            RemIndex = cell_instance->instance_oid.id[4] - 1;
            value_len = LWIP_LLDP_CIP_MAC_TLV_LEN;
            memcpy((void *)value, (void *)&glldp_agent.rx.remote_system_mib[RemIndex].cip_mac_address[0], (size_t)value_len);
         }
         break;
      case 8:
         {
            /* lldpXOdvaRemCIPInterfaceLabel */
            RemIndex = cell_instance->instance_oid.id[4] - 1;
            value_len = (s16_t) glldp_agent.rx.remote_system_mib[RemIndex].cip_if_label_len;
            memcpy((void *)value, (void *)glldp_agent.rx.remote_system_mib[RemIndex].cip_if_label, (size_t)value_len);
         }
         break;
      case 9:
         {
            /* lldpXOdvaRemCIPPositionID */
             u32_t *v = (u32_t *)value;

            RemIndex = cell_instance->instance_oid.id[4] - 1;
            value_len = sizeof(u32_t);
            *v = (u32_t) glldp_agent.rx.remote_system_mib[RemIndex].cip_posision_id;
         }
         break;
      case 10:
         {
            /* lldpXOdvaRemCIPPHYMode */
             u32_t *v = (u32_t *)value;

            RemIndex = cell_instance->instance_oid.id[4] - 1;
            value_len = sizeof(u32_t);
            *v = (u32_t) glldp_agent.rx.remote_system_mib[RemIndex].cip_phy_mode;
         }
         break;
      case 11:
         {
            /* lldpXOdvaRemCIPPLCAPHYNodeID */
             u32_t *v = (u32_t *)value;

            RemIndex = cell_instance->instance_oid.id[4] - 1;
            value_len = sizeof(u32_t);
            *v = (u32_t) glldp_agent.rx.remote_system_mib[RemIndex].cip_phy_node_id;
         }
         break;
      default:
         {
            LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpxodvaremtable_get_value(): unknown id: %"S32_F"\n", SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id)));
            value_len = 0;
         }
         break;
   }
   return value_len;
}

/* --- lldpXOdvaObjects 1.0.8802.1.1.2.1.5.8556.1 ----------------------------------------------------- */
/* --- lldpXOdvaMIB  ----------------------------------------------------- */
#endif /* LWIP_LLDP_SUPPORT_CIP_TLV */
#endif /* LWIP_SNMP */
