/*
Generated by LwipMibCompiler
*/

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP && LWIP_LLDP

#include "lldp-mib.h"
#include "lwip/apps/snmp.h"
#include "lwip/apps/snmp_core.h"
#include "lwip/apps/snmp_scalar.h"
#include "lwip/apps/snmp_table.h"
#include "lwip/netif.h"
#include "lwip_lldp_mib.h"
#include "lwip_lldp_def.h"

/* --- lldpConfiguration 1.0.8802.1.1.2.1.1 ----------------------------------------------------- */
static s16_t lldpconfiguration_treenode_get_value(struct snmp_node_instance *instance, void *value);
static snmp_err_t lldpconfiguration_treenode_set_test(struct snmp_node_instance *instance, u16_t len, void *value);
static snmp_err_t lldpconfiguration_treenode_set_value(struct snmp_node_instance *instance, u16_t len, void *value);
static const struct snmp_scalar_node lldpmessagetxinterval_scalar = SNMP_SCALAR_CREATE_NODE(1, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_INTEGER, lldpconfiguration_treenode_get_value, lldpconfiguration_treenode_set_test, lldpconfiguration_treenode_set_value);

static const struct snmp_scalar_node lldpmessagetxholdmultiplier_scalar = SNMP_SCALAR_CREATE_NODE(2, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_INTEGER, lldpconfiguration_treenode_get_value, lldpconfiguration_treenode_set_test, lldpconfiguration_treenode_set_value);

static const struct snmp_scalar_node lldpreinitdelay_scalar = SNMP_SCALAR_CREATE_NODE(3, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_INTEGER, lldpconfiguration_treenode_get_value, lldpconfiguration_treenode_set_test, lldpconfiguration_treenode_set_value);

static const struct snmp_scalar_node lldptxdelay_scalar = SNMP_SCALAR_CREATE_NODE(4, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_INTEGER, lldpconfiguration_treenode_get_value, lldpconfiguration_treenode_set_test, lldpconfiguration_treenode_set_value);

static const struct snmp_scalar_node lldpnotificationinterval_scalar = SNMP_SCALAR_CREATE_NODE(5, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_INTEGER, lldpconfiguration_treenode_get_value, lldpconfiguration_treenode_set_test, lldpconfiguration_treenode_set_value);

static snmp_err_t lldpportconfigtable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance);
static snmp_err_t lldpportconfigtable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance);
static s16_t lldpportconfigtable_get_value(struct snmp_node_instance *cell_instance, void *value);
static snmp_err_t lldpportconfigtable_set_test(struct snmp_node_instance *cell_instance, u16_t len, void *value);
static snmp_err_t lldpportconfigtable_set_value(struct snmp_node_instance *cell_instance, u16_t len, void *value);
static const struct snmp_table_col_def lldpportconfigtable_columns[] = {
  {2, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE}, /* lldpPortConfigAdminStatus */ 
  {3, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE}, /* lldpPortConfigNotificationEnable */ 
  {4, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* lldpPortConfigTLVsTxEnable */ 
};
static const struct snmp_table_node lldpportconfigtable = SNMP_TABLE_CREATE(6, lldpportconfigtable_columns, lldpportconfigtable_get_instance, lldpportconfigtable_get_next_instance, lldpportconfigtable_get_value, lldpportconfigtable_set_test, lldpportconfigtable_set_value);

static snmp_err_t lldpconfigmanaddrtable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance);
static snmp_err_t lldpconfigmanaddrtable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance);
static s16_t lldpconfigmanaddrtable_get_value(struct snmp_node_instance *cell_instance, void *value);
static snmp_err_t lldpconfigmanaddrtable_set_test(struct snmp_node_instance *cell_instance, u16_t len, void *value);
static snmp_err_t lldpconfigmanaddrtable_set_value(struct snmp_node_instance *cell_instance, u16_t len, void *value);
static const struct snmp_table_col_def lldpconfigmanaddrtable_columns[] = {
  {1, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* lldpConfigManAddrPortsTxEnable */ 
};
static const struct snmp_table_node lldpconfigmanaddrtable = SNMP_TABLE_CREATE(7, lldpconfigmanaddrtable_columns, lldpconfigmanaddrtable_get_instance, lldpconfigmanaddrtable_get_next_instance, lldpconfigmanaddrtable_get_value, lldpconfigmanaddrtable_set_test, lldpconfigmanaddrtable_set_value);

static const struct snmp_node *const lldpconfiguration_subnodes[] = {
  &lldpmessagetxinterval_scalar.node.node,
  &lldpmessagetxholdmultiplier_scalar.node.node,
  &lldpreinitdelay_scalar.node.node,
  &lldptxdelay_scalar.node.node,
  &lldpnotificationinterval_scalar.node.node,
  &lldpportconfigtable.node.node,
  &lldpconfigmanaddrtable.node.node
};
static const struct snmp_tree_node lldpconfiguration_treenode = SNMP_CREATE_TREE_NODE(1, lldpconfiguration_subnodes);

/* --- lldpStatistics 1.0.8802.1.1.2.1.2 ----------------------------------------------------- */
static s16_t lldpstatistics_treenode_get_value(struct snmp_node_instance *instance, void *value);
static const struct snmp_scalar_node lldpstatsremtableslastchangetime_scalar = SNMP_SCALAR_CREATE_NODE_READONLY(1, SNMP_ASN1_TYPE_TIMETICKS, lldpstatistics_treenode_get_value);

static const struct snmp_scalar_node lldpstatsremtablesinserts_scalar = SNMP_SCALAR_CREATE_NODE_READONLY(2, SNMP_ASN1_TYPE_GAUGE, lldpstatistics_treenode_get_value);

static const struct snmp_scalar_node lldpstatsremtablesdeletes_scalar = SNMP_SCALAR_CREATE_NODE_READONLY(3, SNMP_ASN1_TYPE_GAUGE, lldpstatistics_treenode_get_value);

static const struct snmp_scalar_node lldpstatsremtablesdrops_scalar = SNMP_SCALAR_CREATE_NODE_READONLY(4, SNMP_ASN1_TYPE_GAUGE, lldpstatistics_treenode_get_value);

static const struct snmp_scalar_node lldpstatsremtablesageouts_scalar = SNMP_SCALAR_CREATE_NODE_READONLY(5, SNMP_ASN1_TYPE_GAUGE, lldpstatistics_treenode_get_value);

static snmp_err_t lldpstatstxporttable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance);
static snmp_err_t lldpstatstxporttable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance);
static s16_t lldpstatstxporttable_get_value(struct snmp_node_instance *cell_instance, void *value);
static const struct snmp_table_col_def lldpstatstxporttable_columns[] = {
  {2, SNMP_ASN1_TYPE_COUNTER, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpStatsTxPortFramesTotal */ 
};
static const struct snmp_table_node lldpstatstxporttable = SNMP_TABLE_CREATE(6, lldpstatstxporttable_columns, lldpstatstxporttable_get_instance, lldpstatstxporttable_get_next_instance, lldpstatstxporttable_get_value, NULL, NULL);

static snmp_err_t lldpstatsrxporttable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance);
static snmp_err_t lldpstatsrxporttable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance);
static s16_t lldpstatsrxporttable_get_value(struct snmp_node_instance *cell_instance, void *value);
static const struct snmp_table_col_def lldpstatsrxporttable_columns[] = {
  {2, SNMP_ASN1_TYPE_COUNTER, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpStatsRxPortFramesDiscardedTotal */ 
  {3, SNMP_ASN1_TYPE_COUNTER, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpStatsRxPortFramesErrors */ 
  {4, SNMP_ASN1_TYPE_COUNTER, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpStatsRxPortFramesTotal */ 
  {5, SNMP_ASN1_TYPE_COUNTER, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpStatsRxPortTLVsDiscardedTotal */ 
  {6, SNMP_ASN1_TYPE_COUNTER, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpStatsRxPortTLVsUnrecognizedTotal */ 
  {7, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpStatsRxPortAgeoutsTotal */ 
};
static const struct snmp_table_node lldpstatsrxporttable = SNMP_TABLE_CREATE(7, lldpstatsrxporttable_columns, lldpstatsrxporttable_get_instance, lldpstatsrxporttable_get_next_instance, lldpstatsrxporttable_get_value, NULL, NULL);

static const struct snmp_node *const lldpstatistics_subnodes[] = {
  &lldpstatsremtableslastchangetime_scalar.node.node,
  &lldpstatsremtablesinserts_scalar.node.node,
  &lldpstatsremtablesdeletes_scalar.node.node,
  &lldpstatsremtablesdrops_scalar.node.node,
  &lldpstatsremtablesageouts_scalar.node.node,
  &lldpstatstxporttable.node.node,
  &lldpstatsrxporttable.node.node
};
static const struct snmp_tree_node lldpstatistics_treenode = SNMP_CREATE_TREE_NODE(2, lldpstatistics_subnodes);

/* --- lldpLocalSystemData 1.0.8802.1.1.2.1.3 ----------------------------------------------------- */
static s16_t lldplocalsystemdata_treenode_get_value(struct snmp_node_instance *instance, void *value);
static const struct snmp_scalar_node lldplocchassisidsubtype_scalar = SNMP_SCALAR_CREATE_NODE_READONLY(1, SNMP_ASN1_TYPE_INTEGER, lldplocalsystemdata_treenode_get_value);

static const struct snmp_scalar_node lldplocchassisid_scalar = SNMP_SCALAR_CREATE_NODE_READONLY(2, SNMP_ASN1_TYPE_OCTET_STRING, lldplocalsystemdata_treenode_get_value);

static const struct snmp_scalar_node lldplocsysname_scalar = SNMP_SCALAR_CREATE_NODE_READONLY(3, SNMP_ASN1_TYPE_OCTET_STRING, lldplocalsystemdata_treenode_get_value);

static const struct snmp_scalar_node lldplocsysdesc_scalar = SNMP_SCALAR_CREATE_NODE_READONLY(4, SNMP_ASN1_TYPE_OCTET_STRING, lldplocalsystemdata_treenode_get_value);

static const struct snmp_scalar_node lldplocsyscapsupported_scalar = SNMP_SCALAR_CREATE_NODE_READONLY(5, SNMP_ASN1_TYPE_OCTET_STRING, lldplocalsystemdata_treenode_get_value);

static const struct snmp_scalar_node lldplocsyscapenabled_scalar = SNMP_SCALAR_CREATE_NODE_READONLY(6, SNMP_ASN1_TYPE_OCTET_STRING, lldplocalsystemdata_treenode_get_value);

static snmp_err_t lldplocporttable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance);
static snmp_err_t lldplocporttable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance);
static s16_t lldplocporttable_get_value(struct snmp_node_instance *cell_instance, void *value);
static const struct snmp_table_col_def lldplocporttable_columns[] = {
  {2, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpLocPortIdSubtype */ 
  {3, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpLocPortId */ 
  {4, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpLocPortDesc */ 
};
static const struct snmp_table_node lldplocporttable = SNMP_TABLE_CREATE(7, lldplocporttable_columns, lldplocporttable_get_instance, lldplocporttable_get_next_instance, lldplocporttable_get_value, NULL, NULL);

static snmp_err_t lldplocmanaddrtable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance);
static snmp_err_t lldplocmanaddrtable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance);
static s16_t lldplocmanaddrtable_get_value(struct snmp_node_instance *cell_instance, void *value);
static const struct snmp_table_col_def lldplocmanaddrtable_columns[] = {
  {3, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpLocManAddrLen */ 
  {4, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpLocManAddrIfSubtype */ 
  {5, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpLocManAddrIfId */ 
  {6, SNMP_ASN1_TYPE_OBJECT_ID, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpLocManAddrOID */ 
};
static const struct snmp_table_node lldplocmanaddrtable = SNMP_TABLE_CREATE(8, lldplocmanaddrtable_columns, lldplocmanaddrtable_get_instance, lldplocmanaddrtable_get_next_instance, lldplocmanaddrtable_get_value, NULL, NULL);

static const struct snmp_node *const lldplocalsystemdata_subnodes[] = {
  &lldplocchassisidsubtype_scalar.node.node,
  &lldplocchassisid_scalar.node.node,
  &lldplocsysname_scalar.node.node,
  &lldplocsysdesc_scalar.node.node,
  &lldplocsyscapsupported_scalar.node.node,
  &lldplocsyscapenabled_scalar.node.node,
  &lldplocporttable.node.node,
  &lldplocmanaddrtable.node.node
};
static const struct snmp_tree_node lldplocalsystemdata_treenode = SNMP_CREATE_TREE_NODE(3, lldplocalsystemdata_subnodes);

/* --- lldpRemoteSystemsData 1.0.8802.1.1.2.1.4 ----------------------------------------------------- */
static snmp_err_t lldpremtable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance);
static snmp_err_t lldpremtable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance);
static s16_t lldpremtable_get_value(struct snmp_node_instance *cell_instance, void *value);
static const struct snmp_table_col_def lldpremtable_columns[] = {
  {4, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpRemChassisIdSubtype */ 
  {5, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpRemChassisId */ 
  {6, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpRemPortIdSubtype */ 
  {7, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpRemPortId */ 
  {8, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpRemPortDesc */ 
  {9, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpRemSysName */ 
  {10, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpRemSysDesc */ 
  {11, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpRemSysCapSupported */ 
  {12, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpRemSysCapEnabled */ 
};
static const struct snmp_table_node lldpremtable = SNMP_TABLE_CREATE(1, lldpremtable_columns, lldpremtable_get_instance, lldpremtable_get_next_instance, lldpremtable_get_value, NULL, NULL);

static snmp_err_t lldpremmanaddrtable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance);
static snmp_err_t lldpremmanaddrtable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance);
static s16_t lldpremmanaddrtable_get_value(struct snmp_node_instance *cell_instance, void *value);
static const struct snmp_table_col_def lldpremmanaddrtable_columns[] = {
  {3, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpRemManAddrIfSubtype */ 
  {4, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpRemManAddrIfId */ 
  {5, SNMP_ASN1_TYPE_OBJECT_ID, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpRemManAddrOID */ 
};
static const struct snmp_table_node lldpremmanaddrtable = SNMP_TABLE_CREATE(2, lldpremmanaddrtable_columns, lldpremmanaddrtable_get_instance, lldpremmanaddrtable_get_next_instance, lldpremmanaddrtable_get_value, NULL, NULL);

static snmp_err_t lldpremunknowntlvtable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance);
static snmp_err_t lldpremunknowntlvtable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance);
static s16_t lldpremunknowntlvtable_get_value(struct snmp_node_instance *cell_instance, void *value);
static const struct snmp_table_col_def lldpremunknowntlvtable_columns[] = {
  {2, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpRemUnknownTLVInfo */ 
};
static const struct snmp_table_node lldpremunknowntlvtable = SNMP_TABLE_CREATE(3, lldpremunknowntlvtable_columns, lldpremunknowntlvtable_get_instance, lldpremunknowntlvtable_get_next_instance, lldpremunknowntlvtable_get_value, NULL, NULL);

static snmp_err_t lldpremorgdefinfotable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance);
static snmp_err_t lldpremorgdefinfotable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance);
static s16_t lldpremorgdefinfotable_get_value(struct snmp_node_instance *cell_instance, void *value);
static const struct snmp_table_col_def lldpremorgdefinfotable_columns[] = {
  {4, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* lldpRemOrgDefInfo */ 
};
static const struct snmp_table_node lldpremorgdefinfotable = SNMP_TABLE_CREATE(4, lldpremorgdefinfotable_columns, lldpremorgdefinfotable_get_instance, lldpremorgdefinfotable_get_next_instance, lldpremorgdefinfotable_get_value, NULL, NULL);

static const struct snmp_node *const lldpremotesystemsdata_subnodes[] = {
  &lldpremtable.node.node,
  &lldpremmanaddrtable.node.node,
  &lldpremunknowntlvtable.node.node,
  &lldpremorgdefinfotable.node.node
};
static const struct snmp_tree_node lldpremotesystemsdata_treenode = SNMP_CREATE_TREE_NODE(4, lldpremotesystemsdata_subnodes);

/* --- lldpObjects 1.0.8802.1.1.2.1 ----------------------------------------------------- */
static const struct snmp_node *const lldpobjects_subnodes[] = {
  &lldpconfiguration_treenode.node,
  &lldpstatistics_treenode.node,
  &lldplocalsystemdata_treenode.node,
  &lldpremotesystemsdata_treenode.node
};
static const struct snmp_tree_node lldpobjects_treenode = SNMP_CREATE_TREE_NODE(1, lldpobjects_subnodes);

/* --- lldpMIB  ----------------------------------------------------- */
static const struct snmp_node *const lldpmib_subnodes[] = {
  &lldpobjects_treenode.node
};
static const struct snmp_tree_node lldpmib_root = SNMP_CREATE_TREE_NODE(2, lldpmib_subnodes);
static const u32_t lldpmib_base_oid[] = {1,0,8802,1,1,2};
const struct snmp_mib lldpmib = {lldpmib_base_oid, LWIP_ARRAYSIZE(lldpmib_base_oid), &lldpmib_root.node};

static LWIP_LLDP_AGENT_VARIABLES glldp_agent = {0};



/*
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
LWIP MIB generator - preserved section begin
Code below is preserved on regeneration. Remove these comment lines to regenerate code.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
*/

static err_t lldp_mib_asn1_dec_oid(u8_t *pbuf, u16_t len, u32_t *oid, u8_t *oid_len, u8_t oid_max_len)
{
  u32_t *oid_ptr;
  u8_t data;

  *oid_len = 0;
  oid_ptr = oid;
  if (len > 0) {
    if (oid_max_len < 2) {
      return ERR_MEM;
    }

    data = pbuf[0];
    len--;

    /* first compressed octet */
    if (data == 0x2B) {
      /* (most) common case 1.3 (iso.org) */
      *oid_ptr = 1;
      oid_ptr++;
      *oid_ptr = 3;
      oid_ptr++;
    } else if (data < 40) {
      *oid_ptr = 0;
      oid_ptr++;
      *oid_ptr = data;
      oid_ptr++;
    } else if (data < 80) {
      *oid_ptr = 1;
      oid_ptr++;
      *oid_ptr = data - 40;
      oid_ptr++;
    } else {
      *oid_ptr = 2;
      oid_ptr++;
      *oid_ptr = data - 80;
      oid_ptr++;
    }
    *oid_len = 2;
  } else {
    /* accepting zero length identifiers e.g. for getnext operation. uncommon but valid */
    return ERR_OK;
  }

  while ((len > 0) && (*oid_len < oid_max_len)) {
    pbuf++;
    data = pbuf[0];
    len--;

    if ((data & 0x80) == 0x00) {
      /* sub-identifier uses single octet */
      *oid_ptr = data;
    } else {
      /* sub-identifier uses multiple octets */
      u32_t sub_id = (u32_t)(data & ~0x80);
      while ((len > 0) && ((data & 0x80) != 0)) {
        pbuf++;
        data = pbuf[0];
        len--;

        sub_id = (sub_id << 7) + (u32_t)(data & ~0x80);
      }

      if ((data & 0x80) != 0) {
        /* "more bytes following" bit still set at end of len */
        return ERR_VAL;
      }
      *oid_ptr = sub_id;
    }
    oid_ptr++;
    (*oid_len)++;
  }

  if (len > 0) {
    /* OID to long to fit in our buffer */
    return ERR_MEM;
  }

  return ERR_OK;
}

/* --- lldpConfiguration 1.0.8802.1.1.2.1.1 ----------------------------------------------------- */

/* list of allowed value ranges for incoming OID */
static const struct snmp_oid_range lldpportconfig_Table_oid_ranges[] = {
  { 1, 0x1000 } /* lldpPortConfigPortNum */
};

static snmp_err_t lldpportconfigtable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance)
{
  u32_t lldp_port_id;
  struct netif *netif;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid, row_oid_len, lldpportconfig_Table_oid_ranges, LWIP_ARRAYSIZE(lldpportconfig_Table_oid_ranges))) {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* get netif lldp port identifier from incoming OID */
  lldp_port_id = row_oid[0];

  /* find netif with index */
  NETIF_FOREACH(netif) {
    if (netif->lldp_port_id != 0) {
      if (netif->lldp_port_id == lldp_port_id) {
        /* store netif pointer for subsequent operations (get/test/set) */
        cell_instance->reference.ptr = netif;
        return SNMP_ERR_NOERROR;
      }
    }
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static snmp_err_t lldpportconfigtable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance)
{
  struct netif *netif;
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(lldpportconfig_Table_oid_ranges)];

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state, row_oid->id, row_oid->len, result_temp, LWIP_ARRAYSIZE(lldpportconfig_Table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  NETIF_FOREACH(netif) {
    if (netif->lldp_port_id != 0) {
      u32_t test_oid[LWIP_ARRAYSIZE(lldpportconfig_Table_oid_ranges)];
      test_oid[0] = netif->lldp_port_id;

      /* check generated OID: is it a candidate for the next one? */
      snmp_next_oid_check(&state, test_oid, LWIP_ARRAYSIZE(lldpportconfig_Table_oid_ranges), netif);
    }
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS) {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    /* store netif pointer for subsequent operations (get/test/set) */
    cell_instance->reference.ptr = /* (struct netif*) */state.reference;
    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static s16_t lldpportconfigtable_get_value(struct snmp_node_instance *cell_instance, void *value)
{
  struct netif *netif = (struct netif *)cell_instance->reference.ptr;
  s16_t value_len;

  memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
  if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
    LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
  }

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
  case 2:
    {
      /* lldpPortConfigAdminStatus */
      s32_t *v = (s32_t *)value;

      value_len = sizeof(s32_t);
      *v = (s32_t)glldp_agent.global.adminStatus;
    }
    break;
  case 3:
    {
      /* lldpPortConfigNotificationEnable */
      s32_t *v = (s32_t *)value;

      snmp_encode_truthvalue(v, glldp_agent.rx.notification.enable);
      value_len = sizeof(s32_t);
    }
    break;
  case 4:
    {
      /* lldpPortConfigTLVsTxEnable */

      value_len = snmp_encode_bits((u8_t *)value, SNMP_MAX_VALUE_SIZE, glldp_agent.tlv.mibBasicTLVsTxEnable, 4);
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpportconfigtable_get_value(): unknown id: %"S32_F"\n", SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id)));
      value_len = 0;
    }
    break;
  }
  return value_len;
}static snmp_err_t lldpportconfigtable_set_test(struct snmp_node_instance *cell_instance, u16_t len, void *value)
{
  snmp_err_t err = SNMP_ERR_WRONGVALUE;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
  case 2:
    {
      /* lldpPortConfigAdminStatus */
      s32_t *v = (s32_t *)value;

      LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
      if (((*v >= 1) && (*v <= 4)))
      {
        err = SNMP_ERR_NOERROR;
      }
    }
    break;
  case 3:
    {
      /* lldpPortConfigNotificationEnable */
      s32_t *v = (s32_t *)value;

      LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
      if (((*v >= 1) && (*v <= 2)))
      {
        err = SNMP_ERR_NOERROR;
      }
    }
    break;
  case 4:
    {
      /* lldpPortConfigTLVsTxEnable */
      u32_t bits;

      if (snmp_decode_bits((u8_t *)value, len, &bits) == ERR_OK)
      {
        if (((bits & 15) == bits))
        {
          err = SNMP_ERR_NOERROR;
        }
      }
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpportconfigtable_set_test(): unknown id: %"S32_F"\n", SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id)));
    }
    break;
  }
  return err;
}static snmp_err_t lldpportconfigtable_set_value(struct snmp_node_instance *cell_instance, u16_t len, void *value)
{
  snmp_err_t err = SNMP_ERR_NOERROR;
  struct netif *netif = (struct netif *)cell_instance->reference.ptr;

  memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
  if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
    LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
  }

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
  case 2:
    {
      /* lldpPortConfigAdminStatus */
      s32_t *v = (s32_t *)value;

      glldp_agent.global.adminStatus = *v;
      glldp_agent.global.snmpChangeStatus = true;
      if (LWIP_LLDP_mib_set_request(netif->lldp_port_id, &glldp_agent) == 0) {
        if (LWIP_LLDP_mib_set_response(netif->lldp_port_id) != 0) {
          err = SNMP_ERR_RESOURCEUNAVAILABLE;
        }
      } else {
        err = SNMP_ERR_RESOURCEUNAVAILABLE;
      }
    }
    break;
  case 3:
    {
      /* lldpPortConfigNotificationEnable */
      s32_t *v = (s32_t *)value;
      u8_t bool_value;

      snmp_decode_truthvalue(v, &bool_value);
      glldp_agent.rx.notification.enable = (bool)bool_value;
      if (LWIP_LLDP_mib_set_request(netif->lldp_port_id, &glldp_agent) == 0) {
        if (LWIP_LLDP_mib_set_response(netif->lldp_port_id) != 0) {
          err = SNMP_ERR_RESOURCEUNAVAILABLE;
        }
      } else {
        err = SNMP_ERR_RESOURCEUNAVAILABLE;
      }
    }
    break;
  case 4:
    {
      /* lldpPortConfigTLVsTxEnable */
      u32_t bits;

      if (snmp_decode_bits((u8_t *)value, len, &bits) == ERR_OK)
      {
        glldp_agent.tlv.mibBasicTLVsTxEnable = (uint8_t)bits;
        if (LWIP_LLDP_mib_set_request(netif->lldp_port_id, &glldp_agent) == 0) {
          if (LWIP_LLDP_mib_set_response(netif->lldp_port_id) != 0) {
            err = SNMP_ERR_RESOURCEUNAVAILABLE;
          }
        } else {
          err = SNMP_ERR_RESOURCEUNAVAILABLE;
        }
      }
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpportconfigtable_set_value(): unknown id: %"S32_F"\n", SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id)));
    }
    break;
  }
  return err;
}
static snmp_err_t lldpconfigmanaddrtable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance)
{
  ip_addr_t local_ip;
  struct netif *netif;
  u8_t idx = 0;

  LWIP_UNUSED_ARG(column);

  /* lldpLocManAddrSubtype + lldpLocManAddr */
  idx += snmp_oid_to_ip(&row_oid[idx], row_oid_len - idx, &local_ip);
  if (idx == 0) {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* find netif with index */
  NETIF_FOREACH(netif) {
    if (netif->hwaddr_len != 0) {
      if (!ip4_addr_isany_val(*netif_ip4_addr(netif))) {
        if (ip_addr_cmp(&local_ip, netif_ip4_addr(netif))) {
          /* store netif pointer for subsequent operations (get/test/set) */
          cell_instance->reference.ptr = netif;
          return SNMP_ERR_NOERROR;
        }
      }
    }
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static snmp_err_t lldpconfigmanaddrtable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance)
{
  struct netif *netif;
  struct snmp_next_oid_state state;
  /* 1x lldpLocManAddrSubtype + 1x OID len + 16x lldpLocManAddr = 18 */
  u32_t result_temp[18];

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state, row_oid->id, row_oid->len, result_temp, LWIP_ARRAYSIZE(result_temp));

  /* iterate over all possible OIDs to find the next one */
  NETIF_FOREACH(netif) {
    if (netif->hwaddr_len != 0) {
      if (!ip4_addr_isany_val(*netif_ip4_addr(netif))) {
        u32_t test_oid[LWIP_ARRAYSIZE(result_temp)];
        u8_t idx = 0;

        /* lldpLocManAddrSubtype + lldpLocManAddr */
        idx += snmp_ip_to_oid(netif_ip4_addr(netif), &test_oid[idx]);

        /* check generated OID: is it a candidate for the next one? */
        snmp_next_oid_check(&state, test_oid, idx, netif);
      }
    }
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS) {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    /* store netif pointer for subsequent operations (get/test/set) */
    cell_instance->reference.ptr = /* (struct netif*) */state.reference;
    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static s16_t lldpconfigmanaddrtable_get_value(struct snmp_node_instance *cell_instance, void *value)
{
  s16_t value_len = 0;
  u8_t i = 0;
  u8_t enable_port = 0;

  for (i = 0; i < 8; i++) {
    memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
    if (LWIP_LLDP_mib_get_request(i + 1) == 0) {
      LWIP_LLDP_mib_get_response(i + 1, &glldp_agent);
      enable_port |= (((u8_t)glldp_agent.tlv.mibMgmtAddrInstanceTxEnable) << (7 - i));
    }
  }

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
  case 1:
    {
      /* lldpConfigManAddrPortsTxEnable */
      u8_t *v = (u8_t *)value;

      value_len = 1;
      *v = enable_port;
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpconfigmanaddrtable_get_value(): unknown id: %"S32_F"\n", SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id)));
      value_len = 0;
    }
    break;
  }
  return value_len;
}
static snmp_err_t lldpconfigmanaddrtable_set_test(struct snmp_node_instance *cell_instance, u16_t len, void *value)
{
  snmp_err_t err = SNMP_ERR_WRONGVALUE;

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
  case 1:
    {
      /* lldpConfigManAddrPortsTxEnable */
      u8_t *v = (u8_t *)value;

      if (len <= 512)
      {
        err = SNMP_ERR_NOERROR;
      }
      LWIP_UNUSED_ARG(v);
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpconfigmanaddrtable_set_test(): unknown id: %"S32_F"\n", SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id)));
    }
    break;
  }
  return err;
}static snmp_err_t lldpconfigmanaddrtable_set_value(struct snmp_node_instance *cell_instance, u16_t len, void *value)
{
  snmp_err_t err = SNMP_ERR_NOERROR;
  u8_t i = 0;

  LWIP_UNUSED_ARG(len);
  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
  case 1:
    {
      /* lldpConfigManAddrPortsTxEnable */
      u8_t *v = (u8_t *)value;

      err = SNMP_ERR_RESOURCEUNAVAILABLE;
      for (i = 0; i < 8; i++) {
        memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
        if (LWIP_LLDP_mib_get_request(i + 1) == 0) {
          if (LWIP_LLDP_mib_get_response(i + 1, &glldp_agent) == 0) {
            glldp_agent.tlv.mibMgmtAddrInstanceTxEnable = (bool)(*v >> (7 - i));
            if (LWIP_LLDP_mib_set_request(i + 1, &glldp_agent) == 0) {
              if (LWIP_LLDP_mib_set_response(i + 1) == 0) {
                err = SNMP_ERR_NOERROR;
              }
            }
          }
        }
      }
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpconfigmanaddrtable_set_value(): unknown id: %"S32_F"\n", SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id)));
    }
    break;
  }
  return err;
}
static s16_t lldpconfiguration_treenode_get_value(struct snmp_node_instance *instance, void *value)
{
  s16_t value_len = 0;

  memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
  if (LWIP_LLDP_mib_get_request(1) == 0) {
    LWIP_LLDP_mib_get_response(1, &glldp_agent);
  }

  switch (instance->node->oid)
  {
  case 1:
    {
      /* lldpMessageTxInterval */
      s32_t *v = (s32_t *)value;

      value_len = sizeof(s32_t);
#if defined(LWIP_LLDP_CIP_CONNECTED) && 1 != LWIP_LLDP_CIP_CONNECTED
      *v = glldp_agent.tx.tx_parameters.msgTxInterval;
#else
      *v = *glldp_agent.tx.tx_parameters.msgTxInterval;
#endif
    }
    break;
  case 2:
    {
      /* lldpMessageTxHoldMultiplier */
      s32_t *v = (s32_t *)value;

      value_len = sizeof(s32_t);
#if defined(LWIP_LLDP_CIP_CONNECTED) && 1 != LWIP_LLDP_CIP_CONNECTED
      *v = glldp_agent.tx.tx_parameters.msgTxHold;
#else
      *v = *glldp_agent.tx.tx_parameters.msgTxHold;
#endif
    }
    break;
  case 3:
    {
      /* lldpReinitDelay */
      s32_t *v = (s32_t *)value;

      value_len = sizeof(s32_t);
      *v = glldp_agent.tx.tx_parameters.reinitDelay;
    }
    break;
  case 4:
    {
      /* lldpTxDelay */
      s32_t *v = (s32_t *)value;

      value_len = sizeof(s32_t);
      *v = glldp_agent.tx.tx_parameters.txDelay;
    }
    break;
  case 5:
    {
      /* lldpNotificationInterval */
      s32_t *v = (s32_t *)value;

      value_len = sizeof(s32_t);
      *v = glldp_agent.rx.notification.interval;
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpconfiguration_treenode_get_value(): unknown id: %"S32_F"\n", instance->node->oid));
      value_len = 0;
    }
    break;
  }
  return value_len;
}static snmp_err_t lldpconfiguration_treenode_set_test(struct snmp_node_instance *instance, u16_t len, void *value)
{
  snmp_err_t err = SNMP_ERR_WRONGVALUE;

  switch (instance->node->oid)
  {
  case 1:
    {
      /* lldpMessageTxInterval */
      s32_t *v = (s32_t *)value;

      LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
      if (((*v >= 5) && (*v <= 32768)))
      {
        err = SNMP_ERR_NOERROR;
      }
    }
    break;
  case 2:
    {
      /* lldpMessageTxHoldMultiplier */
      s32_t *v = (s32_t *)value;

      LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
      if (((*v >= 2) && (*v <= 10)))
      {
        err = SNMP_ERR_NOERROR;
      }
    }
    break;
  case 3:
    {
      /* lldpReinitDelay */
      s32_t *v = (s32_t *)value;

      LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
      if (((*v >= 1) && (*v <= 10)))
      {
        err = SNMP_ERR_NOERROR;
      }
    }
    break;
  case 4:
    {
      /* lldpTxDelay */
      s32_t *v = (s32_t *)value;

      LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
      if (((*v >= 1) && (*v <= 8192)))
      {
        err = SNMP_ERR_NOERROR;
      }
    }
    break;
  case 5:
    {
      /* lldpNotificationInterval */
      s32_t *v = (s32_t *)value;

      LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
      if (((*v >= 5) && (*v <= 3600)))
      {
        err = SNMP_ERR_NOERROR;
      }
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpconfiguration_treenode_set_test(): unknown id: %"S32_F"\n", instance->node->oid));
    }
    break;
  }
  return err;
}static snmp_err_t lldpconfiguration_treenode_set_value(struct snmp_node_instance *instance, u16_t len, void *value)
{
  snmp_err_t err = SNMP_ERR_NOERROR;
  u8_t i = 0;

  LWIP_UNUSED_ARG(len);
  switch (instance->node->oid)
  {
  case 1:
    {
      /* lldpMessageTxInterval */
      s32_t *v = (s32_t *)value;

      for (i = 0; i < 8; i++) {
        memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
        if (LWIP_LLDP_mib_get_request(i + 1) == 0) {
          LWIP_LLDP_mib_get_response(i + 1, &glldp_agent);

#if defined(LWIP_LLDP_CIP_CONNECTED) && 1 != LWIP_LLDP_CIP_CONNECTED
          glldp_agent.tx.tx_parameters.msgTxInterval = *v;
#else
      	  *glldp_agent.tx.tx_parameters.msgTxInterval = (CipUint)*v;
#endif

          if (LWIP_LLDP_mib_set_request(i + 1, &glldp_agent) == 0) {
            if (LWIP_LLDP_mib_set_response(i + 1) != 0) {
              err = SNMP_ERR_RESOURCEUNAVAILABLE;
              break;
            }
          } else {
            err = SNMP_ERR_RESOURCEUNAVAILABLE;
            break;
          }
        }
      }
    }
    break;
  case 2:
    {
      /* lldpMessageTxHoldMultiplier */
      s32_t *v = (s32_t *)value;

      for (i = 0; i < 8; i++) {
        memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
        if (LWIP_LLDP_mib_get_request(i + 1) == 0) {
          LWIP_LLDP_mib_get_response(i + 1, &glldp_agent);

#if defined(LWIP_LLDP_CIP_CONNECTED) && 1 != LWIP_LLDP_CIP_CONNECTED
          glldp_agent.tx.tx_parameters.msgTxHold = *v;
#else
          *glldp_agent.tx.tx_parameters.msgTxHold = (CipUsint) *v;
#endif

          if (LWIP_LLDP_mib_set_request(i + 1, &glldp_agent) == 0) {
            if (LWIP_LLDP_mib_set_response(i + 1) != 0) {
              err = SNMP_ERR_RESOURCEUNAVAILABLE;
              break;
            }
          } else {
            err = SNMP_ERR_RESOURCEUNAVAILABLE;
            break;
          }
        }
      }
    }
    break;
  case 3:
    {
      /* lldpReinitDelay */
      s32_t *v = (s32_t *)value;

      for (i = 0; i < 8; i++) {
        memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
        if (LWIP_LLDP_mib_get_request(i + 1) == 0) {
          LWIP_LLDP_mib_get_response(i + 1, &glldp_agent);
          glldp_agent.tx.tx_parameters.reinitDelay = *v;
          if (LWIP_LLDP_mib_set_request(i + 1, &glldp_agent) == 0) {
            if (LWIP_LLDP_mib_set_response(i + 1) != 0) {
              err = SNMP_ERR_RESOURCEUNAVAILABLE;
              break;
            }
          } else {
            err = SNMP_ERR_RESOURCEUNAVAILABLE;
            break;
          }
        }
      }
    }
    break;
  case 4:
    {
      /* lldpTxDelay */
      s32_t *v = (s32_t *)value;

      for (i = 0; i < 8; i++) {
        memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
        if (LWIP_LLDP_mib_get_request(i + 1) == 0) {
          LWIP_LLDP_mib_get_response(i + 1, &glldp_agent);
          glldp_agent.tx.tx_parameters.txDelay = *v;
          if (LWIP_LLDP_mib_set_request(i + 1, &glldp_agent) == 0) {
            if (LWIP_LLDP_mib_set_response(i + 1) != 0) {
              err = SNMP_ERR_RESOURCEUNAVAILABLE;
              break;
            }
          } else {
            err = SNMP_ERR_RESOURCEUNAVAILABLE;
            break;
          }
        }
      }
    }
    break;
  case 5:
    {
      /* lldpNotificationInterval */
      s32_t *v = (s32_t *)value;

      for (i = 0; i < 8; i++) {
        memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
        if (LWIP_LLDP_mib_get_request(i + 1) == 0) {
          LWIP_LLDP_mib_get_response(i + 1, &glldp_agent);
          glldp_agent.rx.notification.interval = *v;
          if (LWIP_LLDP_mib_set_request(i + 1, &glldp_agent) == 0) {
            if (LWIP_LLDP_mib_set_response(i + 1) != 0) {
              err = SNMP_ERR_RESOURCEUNAVAILABLE;
              break;
            }
          } else {
            err = SNMP_ERR_RESOURCEUNAVAILABLE;
            break;
          }
        }
      }
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpconfiguration_treenode_set_value(): unknown id: %"S32_F"\n", instance->node->oid));
    }
    break;
  }
  return err;
}
/* --- lldpStatistics 1.0.8802.1.1.2.1.2 ----------------------------------------------------- */

/* list of allowed value ranges for incoming OID */
static const struct snmp_oid_range lldpstatstxport_Table_oid_ranges[] = {
  { 1, 0x1000 } /* lldpStatsTxPortNum */
};

static snmp_err_t lldpstatstxporttable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance)
{
  u32_t lldp_port_id;
  struct netif *netif;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid, row_oid_len, lldpstatstxport_Table_oid_ranges, LWIP_ARRAYSIZE(lldpstatstxport_Table_oid_ranges))) {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* get netif lldp port identifier from incoming OID */
  lldp_port_id = row_oid[0];

  /* find netif with index */
  NETIF_FOREACH(netif) {
    if (netif->lldp_port_id != 0) {
      if (netif->lldp_port_id == lldp_port_id) {
        /* store netif pointer for subsequent operations (get/test/set) */
        cell_instance->reference.ptr = netif;
        return SNMP_ERR_NOERROR;
      }
    }
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static snmp_err_t lldpstatstxporttable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance)
{
  struct netif *netif;
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(lldpstatstxport_Table_oid_ranges)];

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state, row_oid->id, row_oid->len, result_temp, LWIP_ARRAYSIZE(lldpstatstxport_Table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  NETIF_FOREACH(netif) {
    if (netif->lldp_port_id != 0) {
      u32_t test_oid[LWIP_ARRAYSIZE(lldpstatstxport_Table_oid_ranges)];
      test_oid[0] = netif->lldp_port_id;

      /* check generated OID: is it a candidate for the next one? */
      snmp_next_oid_check(&state, test_oid, LWIP_ARRAYSIZE(lldpstatstxport_Table_oid_ranges), netif);
    }
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS) {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    /* store netif pointer for subsequent operations (get/test/set) */
    cell_instance->reference.ptr = /* (struct netif*) */state.reference;
    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static s16_t lldpstatstxporttable_get_value(struct snmp_node_instance *cell_instance, void *value)
{
  struct netif *netif = (struct netif *)cell_instance->reference.ptr;
  s16_t value_len;

  memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
  if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
    LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
  }

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
  case 2:
    {
      /* lldpStatsTxPortFramesTotal */
      u32_t *v = (u32_t *)value;

      value_len = sizeof(u32_t);
      *v = glldp_agent.tx.tx_counters.statsFramesOutTotal;
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpstatstxporttable_get_value(): unknown id: %"S32_F"\n", SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id)));
      value_len = 0;
    }
    break;
  }
  return value_len;
}
/* list of allowed value ranges for incoming OID */
static const struct snmp_oid_range lldpstatsrxport_Table_oid_ranges[] = {
  { 1, 0x1000 } /* lldpStatsRxPortNum */
};

static snmp_err_t lldpstatsrxporttable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance)
{
  u32_t lldp_port_id;
  struct netif *netif;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid, row_oid_len, lldpstatsrxport_Table_oid_ranges, LWIP_ARRAYSIZE(lldpstatsrxport_Table_oid_ranges))) {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* get netif lldp port identifier from incoming OID */
  lldp_port_id = row_oid[0];

  /* find netif with index */
  NETIF_FOREACH(netif) {
    if (netif->lldp_port_id != 0) {
      if (netif->lldp_port_id == lldp_port_id) {
        /* store netif pointer for subsequent operations (get/test/set) */
        cell_instance->reference.ptr = netif;
        return SNMP_ERR_NOERROR;
      }
    }
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static snmp_err_t lldpstatsrxporttable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance)
{
  struct netif *netif;
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(lldpstatsrxport_Table_oid_ranges)];

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state, row_oid->id, row_oid->len, result_temp, LWIP_ARRAYSIZE(lldpstatsrxport_Table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  NETIF_FOREACH(netif) {
    if (netif->lldp_port_id != 0) {
      u32_t test_oid[LWIP_ARRAYSIZE(lldpstatsrxport_Table_oid_ranges)];
      test_oid[0] = netif->lldp_port_id;

      /* check generated OID: is it a candidate for the next one? */
      snmp_next_oid_check(&state, test_oid, LWIP_ARRAYSIZE(lldpstatsrxport_Table_oid_ranges), netif);
    }
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS) {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    /* store netif pointer for subsequent operations (get/test/set) */
    cell_instance->reference.ptr = /* (struct netif*) */state.reference;
    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static s16_t lldpstatsrxporttable_get_value(struct snmp_node_instance *cell_instance, void *value)
{
  struct netif *netif = (struct netif *)cell_instance->reference.ptr;
  s16_t value_len = 0;

  memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
  if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
    LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
  }

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
  case 2:
    {
      /* lldpStatsRxPortFramesDiscardedTotal */
      u32_t *v = (u32_t *)value;

      value_len = sizeof(u32_t);
      *v = glldp_agent.rx.rx_counters.statsFramesDiscardedTotal;
    }
    break;
  case 3:
    {
      /* lldpStatsRxPortFramesErrors */
      u32_t *v = (u32_t *)value;

      value_len = sizeof(u32_t);
      *v = glldp_agent.rx.rx_counters.statsFramesInErrorsTotal;
    }
    break;
  case 4:
    {
      /* lldpStatsRxPortFramesTotal */
      u32_t *v = (u32_t *)value;

      value_len = sizeof(u32_t);
      *v = glldp_agent.rx.rx_counters.statsFramesInTotal;
    }
    break;
  case 5:
    {
      /* lldpStatsRxPortTLVsDiscardedTotal */
      u32_t *v = (u32_t *)value;

      value_len = sizeof(u32_t);
      *v = glldp_agent.rx.rx_counters.statsTLVsDiscardedTotal;
    }
    break;
  case 6:
    {
      /* lldpStatsRxPortTLVsUnrecognizedTotal */
      u32_t *v = (u32_t *)value;

      value_len = sizeof(u32_t);
      *v = glldp_agent.rx.rx_counters.statsTLVsUnrecognizedTotal;
    }
    break;
  case 7:
    {
      /* lldpStatsRxPortAgeoutsTotal */
      u32_t *v = (u32_t *)value;

      value_len = sizeof(u32_t);
      *v = glldp_agent.rx.rx_counters.statsAgeoutsTotal;
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpstatsrxporttable_get_value(): unknown id: %"S32_F"\n", SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id)));
      value_len = 0;
    }
    break;
  }
  return value_len;
}
static s16_t lldpstatistics_treenode_get_value(struct snmp_node_instance *instance, void *value)
{
  s16_t value_len = 0;
  u8_t i = 0;
  LWIP_LLDP_STATS_REM_TABLES stats_rem_tables = {0};

  for (i = 0; i < 8; i++) {
    memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
    if (LWIP_LLDP_mib_get_request(i + 1) == 0) {
      LWIP_LLDP_mib_get_response(i + 1, &glldp_agent);
      stats_rem_tables.last_change_time += glldp_agent.rx.stats_rem_tables.last_change_time;
      stats_rem_tables.inserts          += glldp_agent.rx.stats_rem_tables.inserts;
      stats_rem_tables.deletes          += glldp_agent.rx.stats_rem_tables.deletes;
      stats_rem_tables.drops            += glldp_agent.rx.stats_rem_tables.drops;
      stats_rem_tables.ageouts          += glldp_agent.rx.stats_rem_tables.ageouts;
    }
  }

  switch (instance->node->oid)
  {
  case 1:
    {
      /* lldpStatsRemTablesLastChangeTime */
      u32_t *v = (u32_t *)value;

      value_len = sizeof(u32_t);
      *v = stats_rem_tables.last_change_time;
    }
    break;
  case 2:
    {
      /* lldpStatsRemTablesInserts */
      u32_t *v = (u32_t *)value;

      value_len = sizeof(u32_t);
      *v = stats_rem_tables.inserts;
    }
    break;
  case 3:
    {
      /* lldpStatsRemTablesDeletes */
      u32_t *v = (u32_t *)value;

      value_len = sizeof(u32_t);
      *v = stats_rem_tables.deletes;
    }
    break;
  case 4:
    {
      /* lldpStatsRemTablesDrops */
      u32_t *v = (u32_t *)value;

      value_len = sizeof(u32_t);
      *v = stats_rem_tables.drops;
    }
    break;
  case 5:
    {
      /* lldpStatsRemTablesAgeouts */
      u32_t *v = (u32_t *)value;

      value_len = sizeof(u32_t);
      *v = stats_rem_tables.ageouts;
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpstatistics_treenode_get_value(): unknown id: %"S32_F"\n", instance->node->oid));
      value_len = 0;
    }
    break;
  }
  return value_len;
}
/* --- lldpLocalSystemData 1.0.8802.1.1.2.1.3 ----------------------------------------------------- */

/* list of allowed value ranges for incoming OID */
static const struct snmp_oid_range lldplocport_Table_oid_ranges[] = {
  { 1, 0x1000 } /* lldpLocPortNum */
};

static snmp_err_t lldplocporttable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance)
{
  u32_t lldp_port_id;
  struct netif *netif;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid, row_oid_len, lldplocport_Table_oid_ranges, LWIP_ARRAYSIZE(lldplocport_Table_oid_ranges))) {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* get netif lldp port identifier from incoming OID */
  lldp_port_id = row_oid[0];

  /* find netif with index */
  NETIF_FOREACH(netif) {
    if (netif->lldp_port_id != 0) {
      if (netif->lldp_port_id == lldp_port_id) {
        /* store netif pointer for subsequent operations (get/test/set) */
        cell_instance->reference.ptr = netif;
        return SNMP_ERR_NOERROR;
      }
    }
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static snmp_err_t lldplocporttable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance)
{
  struct netif *netif;
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(lldplocport_Table_oid_ranges)];

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state, row_oid->id, row_oid->len, result_temp, LWIP_ARRAYSIZE(lldplocport_Table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  NETIF_FOREACH(netif) {
    if (netif->lldp_port_id != 0) {
      u32_t test_oid[LWIP_ARRAYSIZE(lldplocport_Table_oid_ranges)];
      test_oid[0] = netif->lldp_port_id;

      /* check generated OID: is it a candidate for the next one? */
      snmp_next_oid_check(&state, test_oid, LWIP_ARRAYSIZE(lldplocport_Table_oid_ranges), netif);
    }
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS) {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    /* store netif pointer for subsequent operations (get/test/set) */
    cell_instance->reference.ptr = /* (struct netif*) */state.reference;
    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static s16_t lldplocporttable_get_value(struct snmp_node_instance *cell_instance, void *value)
{
  struct netif *netif = (struct netif *)cell_instance->reference.ptr;
  s16_t value_len = 0;

  memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
  if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
    LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
  }

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
  case 2:
    {
      /* lldpLocPortIdSubtype */
      s32_t *v = (s32_t *)value;

      value_len = sizeof(s32_t);
      *v = (s32_t)glldp_agent.tx.local_system_mib.port_id_subtype;
    }
    break;
  case 3:
    {
      /* lldpLocPortId */
      value_len = (s16_t)glldp_agent.tx.local_system_mib.port_id_len;
      MEMCPY((void *)value, (void *)glldp_agent.tx.local_system_mib.port_id, (size_t)value_len);
    }
    break;
  case 4:
    {
      /* lldpLocPortDesc */
      value_len = (s16_t)glldp_agent.tx.local_system_mib.port_desc_len;
      MEMCPY((void *)value, (void *)glldp_agent.tx.local_system_mib.port_desc, (size_t)value_len);
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldplocporttable_get_value(): unknown id: %"S32_F"\n", SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id)));
      value_len = 0;
    }
    break;
  }
  return value_len;
}
static snmp_err_t lldplocmanaddrtable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance)
{
  ip_addr_t local_ip;
  struct netif *netif;
  u8_t idx = 0;

  LWIP_UNUSED_ARG(column);

  /* lldpLocManAddrSubtype + lldpLocManAddr */
  idx += snmp_oid_to_ip(&row_oid[idx], row_oid_len - idx, &local_ip);
  if (idx == 0) {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* find netif with index */
  NETIF_FOREACH(netif) {
    if (netif->hwaddr_len != 0) {
      if (!ip4_addr_isany_val(*netif_ip4_addr(netif))) {
        if (ip_addr_cmp(&local_ip, netif_ip4_addr(netif))) {
          /* store netif pointer for subsequent operations (get/test/set) */
          cell_instance->reference.ptr = netif;
          return SNMP_ERR_NOERROR;
        }
      }
    }
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static snmp_err_t lldplocmanaddrtable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance)
{
  struct netif *netif;
  struct snmp_next_oid_state state;
  /* 1x lldpLocManAddrSubtype + 1x OID len + 16x lldpLocManAddr = 18 */
  u32_t result_temp[18];

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state, row_oid->id, row_oid->len, result_temp, LWIP_ARRAYSIZE(result_temp));

  /* iterate over all possible OIDs to find the next one */
  NETIF_FOREACH(netif) {
    if (netif->hwaddr_len != 0) {
      if (!ip4_addr_isany_val(*netif_ip4_addr(netif))) {
        u32_t test_oid[LWIP_ARRAYSIZE(result_temp)];
        u8_t idx = 0;

        /* lldpLocManAddrSubtype + lldpLocManAddr */
        idx += snmp_ip_to_oid(netif_ip4_addr(netif), &test_oid[idx]);

        /* check generated OID: is it a candidate for the next one? */
        snmp_next_oid_check(&state, test_oid, idx, netif);
      }
    }
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS) {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    /* store netif pointer for subsequent operations (get/test/set) */
    cell_instance->reference.ptr = /* (struct netif*) */state.reference;
    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static s16_t lldplocmanaddrtable_get_value(struct snmp_node_instance *cell_instance, void *value)
{
  struct netif *netif = (struct netif *)cell_instance->reference.ptr;
  s16_t value_len = 0;

  memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
  if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
    LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
  }

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
  case 3:
    {
      /* lldpLocManAddrLen */
      s32_t *v = (s32_t *)value;

      value_len = sizeof(s32_t);
      *v = (s32_t)glldp_agent.tx.local_system_mib.mana_add_len;
    }
    break;
  case 4:
    {
      /* lldpLocManAddrIfSubtype */
      s32_t *v = (s32_t *)value;

      value_len = sizeof(s32_t);
      *v = (s32_t)glldp_agent.tx.local_system_mib.interface_num_subtype;
    }
    break;
  case 5:
    {
      /* lldpLocManAddrIfId */
      s32_t *v = (s32_t *)value;

      value_len = sizeof(s32_t);
      *v = (s32_t)glldp_agent.tx.local_system_mib.interface_num;
    }
    break;
  case 6:
    {
      /* lldpLocManAddrOID */
      struct snmp_obj_id oid;

      if (lldp_mib_asn1_dec_oid(&glldp_agent.tx.local_system_mib.oid[0], glldp_agent.tx.local_system_mib.oid_len, (u32_t *)&oid.id[0], &oid.len, SNMP_MAX_OBJ_ID_LEN) == ERR_OK) {
        MEMCPY(value, oid.id, oid.len * sizeof(u32_t));
        return oid.len * sizeof(u32_t); 
      } else {
        value_len = 0;
      }
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldplocmanaddrtable_get_value(): unknown id: %"S32_F"\n", SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id)));
      value_len = 0;
    }
    break;
  }
  return value_len;
}
static s16_t lldplocalsystemdata_treenode_get_value(struct snmp_node_instance *instance, void *value)
{
  s16_t value_len = 0;

  memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
  if (LWIP_LLDP_mib_get_request(1) == 0) {
    LWIP_LLDP_mib_get_response(1, &glldp_agent);
  }

  switch (instance->node->oid)
  {
  case 1:
    {
      /* lldpLocChassisIdSubtype */
      s32_t *v = (s32_t *)value;

      value_len = sizeof(s32_t);
      *v = (s32_t)glldp_agent.tx.local_system_mib.chassis_id_subtype;
    }
    break;
  case 2:
    {
      /* lldpLocChassisId */
      value_len = (s16_t)glldp_agent.tx.local_system_mib.chassis_id_len;
      MEMCPY((void *)value, (void *)glldp_agent.tx.local_system_mib.chassis_id, (size_t)value_len);
    }
    break;
  case 3:
    {
      /* lldpLocSysName */
      value_len = (s16_t)glldp_agent.tx.local_system_mib.system_name_len;
      MEMCPY((void *)value, (void *)glldp_agent.tx.local_system_mib.system_name, (size_t)value_len);
    }
    break;
  case 4:
    {
      /* lldpLocSysDesc */
      value_len = (s16_t)glldp_agent.tx.local_system_mib.system_desc_len;
      MEMCPY((void *)value, (void *)glldp_agent.tx.local_system_mib.system_desc, (size_t)value_len);
    }
    break;
  case 5:
    {
      /* lldpLocSysCapSupported */
      value_len = snmp_encode_bits((u8_t *)value, SNMP_MAX_VALUE_SIZE, glldp_agent.tx.local_system_mib.system_capa, 8);
    }
    break;
  case 6:
    {
      /* lldpLocSysCapEnabled */
      value_len = snmp_encode_bits((u8_t *)value, SNMP_MAX_VALUE_SIZE, glldp_agent.tx.local_system_mib.enabled_capa, 8);
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldplocalsystemdata_treenode_get_value(): unknown id: %"S32_F"\n", instance->node->oid));
      value_len = 0;
    }
    break;
  }
  return value_len;
}
/* --- lldpRemoteSystemsData 1.0.8802.1.1.2.1.4 ----------------------------------------------------- */

/* list of allowed value ranges for incoming OID */
static const struct snmp_oid_range lldprem_Table_oid_ranges[] = {
  { 0, 0xffffffff }, /* lldpRemTimeMark */
  { 1, 0x1000 }, /* lldpRemLocalPortNum */
  { 1, 0x7fffffff } /* lldpRemIndex */
};

static snmp_err_t lldpremtable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance)
{
  struct netif *netif;
  u32_t TimeMark;
  u32_t lldp_port_id;
  u32_t RemIndex;
  u8_t byIndex;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid, row_oid_len, lldprem_Table_oid_ranges, LWIP_ARRAYSIZE(lldprem_Table_oid_ranges))) {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* get netif lldp port identifier from incoming OID */
  TimeMark = row_oid[0];
  lldp_port_id = row_oid[1];
  RemIndex = row_oid[2];

  NETIF_FOREACH(netif) {
    if (netif->lldp_port_id != 0) {
      if (netif->lldp_port_id == lldp_port_id) {
        memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
        if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
          LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
        }
        for (byIndex = 0; byIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS; byIndex++) {
          if (glldp_agent.rx.remote_system_mib_used[byIndex] == false) {
            continue;
          } else {
            if (glldp_agent.rx.rem_time_mark[byIndex] == TimeMark) {
              if ((u32_t)(byIndex + 1) == RemIndex) {
                /* store netif pointer for subsequent operations (get/test/set) */
                cell_instance->reference.ptr = netif;
                return SNMP_ERR_NOERROR;
              }
            }
          }
        }
      }
    }
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static snmp_err_t lldpremtable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance)
{
  struct netif *netif;
  u8_t byIndex;
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(lldprem_Table_oid_ranges)];

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state, row_oid->id, row_oid->len, result_temp, LWIP_ARRAYSIZE(lldprem_Table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  NETIF_FOREACH(netif) {
    if (netif->lldp_port_id != 0) {
      memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
      if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
        LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
      }
      for (byIndex = 0; byIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS; byIndex++) {
        if (glldp_agent.rx.remote_system_mib_used[byIndex] == false) {
          continue;
        } else {
          u32_t test_oid[LWIP_ARRAYSIZE(lldprem_Table_oid_ranges)];

          test_oid[0] = glldp_agent.rx.rem_time_mark[byIndex];
          test_oid[1] = netif->lldp_port_id;
          test_oid[2] = byIndex + 1;

          /* check generated OID: is it a candidate for the next one? */
          snmp_next_oid_check(&state, test_oid, LWIP_ARRAYSIZE(lldprem_Table_oid_ranges), netif);
        }
      }
    }
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS) {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    /* store netif pointer for subsequent operations (get/test/set) */
    cell_instance->reference.ptr = /* (struct netif*) */state.reference;
    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static s16_t lldpremtable_get_value(struct snmp_node_instance *cell_instance, void *value)
{
  struct netif *netif = (struct netif *)cell_instance->reference.ptr;
  s16_t value_len = 0;
  u32_t RemIndex;

  memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
  if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
    LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
  }

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
  case 4:
    {
      /* lldpRemChassisIdSubtype */
      s32_t *v = (s32_t *)value;

      RemIndex = cell_instance->instance_oid.id[4] - 1;
      value_len = sizeof(s32_t);
      if (RemIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS) {
        *v = glldp_agent.rx.remote_system_mib[RemIndex].chassis_id_subtype;
      }
    }
    break;
  case 5:
    {
      /* lldpRemChassisId */
      RemIndex = cell_instance->instance_oid.id[4] - 1;
      if (RemIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS) {
        value_len = (s16_t)glldp_agent.rx.remote_system_mib[RemIndex].chassis_id_len;
        MEMCPY((void *)value, (void *)glldp_agent.rx.remote_system_mib[RemIndex].chassis_id, (size_t)value_len);
      } else {
        value_len = 0;
      }
    }
    break;
  case 6:
    {
      /* lldpRemPortIdSubtype */
      s32_t *v = (s32_t *)value;

      RemIndex = cell_instance->instance_oid.id[4] - 1;
      value_len = sizeof(s32_t);
      if (RemIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS) {
        *v = glldp_agent.rx.remote_system_mib[RemIndex].port_id_subtype;
      }
    }
    break;
  case 7:
    {
      /* lldpRemPortId */
      RemIndex = cell_instance->instance_oid.id[4] - 1;
      if (RemIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS) {
        value_len = (s16_t)glldp_agent.rx.remote_system_mib[RemIndex].port_id_len;
        MEMCPY((void *)value, (void *)glldp_agent.rx.remote_system_mib[RemIndex].port_id, (size_t)value_len);
      } else {
        value_len = 0;
      }
    }
    break;
  case 8:
    {
      /* lldpRemPortDesc */
      RemIndex = cell_instance->instance_oid.id[4] - 1;
      if (RemIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS) {
        value_len = (s16_t)glldp_agent.rx.remote_system_mib[RemIndex].port_desc_len;
        MEMCPY((void *)value, (void *)glldp_agent.rx.remote_system_mib[RemIndex].port_desc, (size_t)value_len);
      } else {
        value_len = 0;
      }
    }
    break;
  case 9:
    {
      /* lldpRemSysName */
      RemIndex = cell_instance->instance_oid.id[4] - 1;
      if (RemIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS) {
        value_len = (s16_t)glldp_agent.rx.remote_system_mib[RemIndex].system_name_len;
        MEMCPY((void *)value, (void *)glldp_agent.rx.remote_system_mib[RemIndex].system_name, (size_t)value_len);
      } else {
        value_len = 0;
      }
    }
    break;
  case 10:
    {
      /* lldpRemSysDesc */
      RemIndex = cell_instance->instance_oid.id[4] - 1;
      if (RemIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS) {
        value_len = (s16_t)glldp_agent.rx.remote_system_mib[RemIndex].system_desc_len;
        MEMCPY((void *)value, (void *)glldp_agent.rx.remote_system_mib[RemIndex].system_desc, (size_t)value_len);
      } else {
        value_len = 0;
      }
    }
    break;
  case 11:
    {
      /* lldpRemSysCapSupported */
      RemIndex = cell_instance->instance_oid.id[4] - 1;
      if (RemIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS) {
        value_len = snmp_encode_bits((u8_t *)value, SNMP_MAX_VALUE_SIZE, glldp_agent.rx.remote_system_mib[RemIndex].system_capa, 8);
      } else {
        value_len = snmp_encode_bits((u8_t *)value, SNMP_MAX_VALUE_SIZE, 0, 8);
      }
    }
    break;
  case 12:
    {
      /* lldpRemSysCapEnabled */
      RemIndex = cell_instance->instance_oid.id[4] - 1;
      if (RemIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS) {
        value_len = snmp_encode_bits((u8_t *)value, SNMP_MAX_VALUE_SIZE, glldp_agent.rx.remote_system_mib[RemIndex].enabled_capa, 8);
      } else {
        value_len = snmp_encode_bits((u8_t *)value, SNMP_MAX_VALUE_SIZE, 0, 8);
      }
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpremtable_get_value(): unknown id: %"S32_F"\n", SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id)));
      value_len = 0;
    }
    break;
  }
  return value_len;
}
/* list of allowed value ranges for incoming OID */
static const struct snmp_oid_range lldpremmanaddr_Table_oid_ranges[] = {
  { 0, 0xffffffff }, /* lldpRemTimeMark */
  { 1, 0x1000 }, /* lldpRemLocalPortNum */
  { 1, 0x7fffffff }, /* lldpRemIndex */
  { 0, 0xffff }, /* lldpRemManAddrSubtype */
  { 0, 0xff }, /* lldpRemManAddr - IP A */
  { 0, 0xff }, /* lldpRemManAddr - IP B */
  { 0, 0xff }, /* lldpRemManAddr - IP C */
  { 0, 0xff }, /* lldpRemManAddr - IP D */
};

static snmp_err_t lldpremmanaddrtable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance)
{
  struct netif *netif;
  u32_t TimeMark;
  u32_t lldp_port_id;
  u32_t RemIndex;
  u32_t RemManAddrSubtype;
  u8_t RemManAddr[4];
  u8_t byIndex;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid, row_oid_len, lldpremmanaddr_Table_oid_ranges, LWIP_ARRAYSIZE(lldpremmanaddr_Table_oid_ranges))) {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* get netif lldp port identifier from incoming OID */
  TimeMark = row_oid[0];
  lldp_port_id = row_oid[1];
  RemIndex = row_oid[2];
  RemManAddrSubtype = row_oid[3];
  RemManAddr[0] = (u8_t)row_oid[4];
  RemManAddr[1] = (u8_t)row_oid[5];
  RemManAddr[2] = (u8_t)row_oid[6];
  RemManAddr[3] = (u8_t)row_oid[7];

  NETIF_FOREACH(netif) {
    if (netif->lldp_port_id != 0) {
      if (netif->lldp_port_id == lldp_port_id) {
        memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
        if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
          LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
        }
        for (byIndex = 0; byIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS; byIndex++) {
          if (glldp_agent.rx.remote_system_mib_used[byIndex] == false) {
            continue;
          } else {
            if (glldp_agent.rx.rem_time_mark[byIndex] == TimeMark) {
              if ((u32_t)(byIndex + 1) == RemIndex) {
                if (glldp_agent.rx.remote_system_mib[byIndex].mana_add_subtype == RemManAddrSubtype) {
                  if (glldp_agent.rx.remote_system_mib[byIndex].mana_add_subtype == LWIP_LLDP_MANA_ADD_SUBTYPE_1) {
                    if (memcmp((void *)&glldp_agent.rx.remote_system_mib[byIndex].mana_add[0], (void *)&RemManAddr[0], sizeof(RemManAddr)) == 0) {
                      /* store netif pointer for subsequent operations (get/test/set) */
                      cell_instance->reference.ptr = netif;
                      return SNMP_ERR_NOERROR;
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static snmp_err_t lldpremmanaddrtable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance)
{
  struct netif *netif;
  u8_t byIndex;
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(lldpremmanaddr_Table_oid_ranges)];

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state, row_oid->id, row_oid->len, result_temp, LWIP_ARRAYSIZE(lldpremmanaddr_Table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  NETIF_FOREACH(netif) {
    if (netif->lldp_port_id != 0) {
      memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
      if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
        LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
      }
      for (byIndex = 0; byIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS; byIndex++) {
        if (glldp_agent.rx.remote_system_mib_used[byIndex] == false) {
          continue;
        } else {
          u32_t test_oid[LWIP_ARRAYSIZE(lldpremmanaddr_Table_oid_ranges)];

          test_oid[0] = glldp_agent.rx.rem_time_mark[byIndex];
          test_oid[1] = netif->lldp_port_id;
          test_oid[2] = byIndex + 1;
          test_oid[3] = glldp_agent.rx.remote_system_mib[byIndex].mana_add_subtype;
          test_oid[4] = glldp_agent.rx.remote_system_mib[byIndex].mana_add[0];
          test_oid[5] = glldp_agent.rx.remote_system_mib[byIndex].mana_add[1];
          test_oid[6] = glldp_agent.rx.remote_system_mib[byIndex].mana_add[2];
          test_oid[7] = glldp_agent.rx.remote_system_mib[byIndex].mana_add[3];

          /* check generated OID: is it a candidate for the next one? */
          snmp_next_oid_check(&state, test_oid, LWIP_ARRAYSIZE(lldpremmanaddr_Table_oid_ranges), netif);
        }
      }
    }
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS) {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    /* store netif pointer for subsequent operations (get/test/set) */
    cell_instance->reference.ptr = /* (struct netif*) */state.reference;
    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static s16_t lldpremmanaddrtable_get_value(struct snmp_node_instance *cell_instance, void *value)
{
  struct netif *netif = (struct netif *)cell_instance->reference.ptr;
  s16_t value_len = 0;
  u32_t RemIndex;

  memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
  if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
    LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
  }

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
  case 3:
    {
      /* lldpRemManAddrIfSubtype */
      s32_t *v = (s32_t *)value;

      RemIndex = cell_instance->instance_oid.id[4] - 1;
      value_len = sizeof(s32_t);
      if (RemIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS) {
        *v = glldp_agent.rx.remote_system_mib[RemIndex].interface_num_subtype;
      }
    }
    break;
  case 4:
    {
      /* lldpRemManAddrIfId */
      s32_t *v = (s32_t *)value;

      RemIndex = cell_instance->instance_oid.id[4] - 1;
      value_len = sizeof(s32_t);
      if (RemIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS) {
        *v = (s32_t) glldp_agent.rx.remote_system_mib[RemIndex].interface_num;
      }
    }
    break;
  case 5:
    {
      /* lldpRemManAddrOID */
      struct snmp_obj_id oid;

      RemIndex = cell_instance->instance_oid.id[4] - 1;
      if (RemIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS) {
        if (lldp_mib_asn1_dec_oid(&glldp_agent.rx.remote_system_mib[RemIndex].oid[0], glldp_agent.rx.remote_system_mib[RemIndex].oid_len, (u32_t *)&oid.id[0], &oid.len, SNMP_MAX_OBJ_ID_LEN) == ERR_OK) {
          MEMCPY(value, oid.id, oid.len * sizeof(u32_t));
          return oid.len * sizeof(u32_t); 
        } else {
          value_len = 0;
        }
      } else {
        value_len = 0;
      }
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpremmanaddrtable_get_value(): unknown id: %"S32_F"\n", SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id)));
      value_len = 0;
    }
    break;
  }
  return value_len;
}
/* list of allowed value ranges for incoming OID */
static const struct snmp_oid_range lldpremunknowntlv_Table_oid_ranges[] = {
  { 0, 0xffffffff }, /* lldpRemTimeMark */
  { 1, 0x1000 }, /* lldpRemLocalPortNum */
  { 1, 0x7fffffff }, /* lldpRemIndex */
  { 9, 126 }, /* lldpRemUnknownTLVType */
};

static snmp_err_t lldpremunknowntlvtable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance)
{
  struct netif *netif;
  u32_t TimeMark;
  u32_t lldp_port_id;
  u32_t RemIndex;
  u32_t RemUnknownTLVType;
  u8_t byIndex;
  u8_t i;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid, row_oid_len, lldpremunknowntlv_Table_oid_ranges, LWIP_ARRAYSIZE(lldpremunknowntlv_Table_oid_ranges))) {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* get netif lldp port identifier from incoming OID */
  TimeMark = row_oid[0];
  lldp_port_id = row_oid[1];
  RemIndex = row_oid[2];
  RemUnknownTLVType = row_oid[3];

  NETIF_FOREACH(netif) {
    if (netif->lldp_port_id != 0) {
      if (netif->lldp_port_id == lldp_port_id) {
        memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
        if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
          LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
        }
        for (byIndex = 0; byIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS; byIndex++) {
          if (glldp_agent.rx.remote_system_mib_used[byIndex] == false) {
            continue;
          } else {
            if (glldp_agent.rx.rem_time_mark[byIndex] == TimeMark) {
              if ((u32_t)(byIndex + 1) == RemIndex) {
                for (i = 0; i < LWIP_LLDP_SUPPORT_RX_MAX_UNKNOWN_TLV_INFO; i++) {
                  if (glldp_agent.rx.remote_system_mib[byIndex].rcv_unknown_tlv[i] == RemUnknownTLVType) {
                    /* store netif pointer for subsequent operations (get/test/set) */
                    cell_instance->reference.ptr = netif;
                    return SNMP_ERR_NOERROR;
                  }
                }
              }
            }
          }
        }
      }
    }
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static snmp_err_t lldpremunknowntlvtable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance)
{
  struct netif *netif;
  u8_t byIndex;
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(lldpremunknowntlv_Table_oid_ranges)];
  u8_t i;

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state, row_oid->id, row_oid->len, result_temp, LWIP_ARRAYSIZE(lldpremunknowntlv_Table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  NETIF_FOREACH(netif) {
    if (netif->lldp_port_id != 0) {
      memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
      if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
        LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
      }
      for (byIndex = 0; byIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS; byIndex++) {
        if (glldp_agent.rx.remote_system_mib_used[byIndex] == false) {
          continue;
        } else {
          for (i = 0; i < LWIP_LLDP_SUPPORT_RX_MAX_UNKNOWN_TLV_INFO; i++) {
            if (glldp_agent.rx.remote_system_mib[byIndex].rcv_unknown_tlv[i] != 0) {
              u32_t test_oid[LWIP_ARRAYSIZE(lldpremunknowntlv_Table_oid_ranges)];

              test_oid[0] = glldp_agent.rx.rem_time_mark[byIndex];
              test_oid[1] = netif->lldp_port_id;
              test_oid[2] = byIndex + 1;
              test_oid[3] = (u32_t)glldp_agent.rx.remote_system_mib[byIndex].rcv_unknown_tlv[i];

              /* check generated OID: is it a candidate for the next one? */
              snmp_next_oid_check(&state, test_oid, LWIP_ARRAYSIZE(lldpremunknowntlv_Table_oid_ranges), netif);
            }
          }
        }
      }
    }
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS) {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    /* store netif pointer for subsequent operations (get/test/set) */
    cell_instance->reference.ptr = /* (struct netif*) */state.reference;
    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static s16_t lldpremunknowntlvtable_get_value(struct snmp_node_instance *cell_instance, void *value)
{
  struct netif *netif = (struct netif *)cell_instance->reference.ptr;
  s16_t value_len = 0;
  u32_t RemIndex;
  u8_t UnknownTLVInfo[LWIP_LLDP_SUPPORT_RX_MAX_UNKNOWN_TLV_INFO];
  u8_t i;

  memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
  if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
    LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
  }

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
  case 2:
    {
      /* lldpRemUnknownTLVInfo */
      RemIndex = cell_instance->instance_oid.id[4] - 1;
      if (RemIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS) {
        for (i = 0; i < LWIP_LLDP_SUPPORT_RX_MAX_UNKNOWN_TLV_INFO; i++) {
          if (glldp_agent.rx.remote_system_mib[RemIndex].rcv_unknown_tlv[i] != 0) {
            value_len++;
            UnknownTLVInfo[i] = glldp_agent.rx.remote_system_mib[RemIndex].rcv_unknown_tlv[i];
          }
        }
        MEMCPY((void *)value, (void *)&UnknownTLVInfo[0], LWIP_LLDP_SUPPORT_RX_MAX_UNKNOWN_TLV_INFO);
      } else {
        value_len = 0;
      }
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpremunknowntlvtable_get_value(): unknown id: %"S32_F"\n", SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id)));
      value_len = 0;
    }
    break;
  }
  return value_len;
}
/* list of allowed value ranges for incoming OID */
static const struct snmp_oid_range lldpremorgdefinfo_Table_oid_ranges[] = {
  { 0, 0xffffffff }, /* lldpRemTimeMark */
  { 1, 0x1000 }, /* lldpRemLocalPortNum */
  { 1, 0x7fffffff }, /* lldpRemIndex */
  { 0, 0xFF }, /* lldpRemOrgDefInfoOUI - 0 */
  { 0, 0xFF }, /* lldpRemOrgDefInfoOUI - 1 */
  { 0, 0xFF }, /* lldpRemOrgDefInfoOUI - 2 */
  { 0, 0xFF }, /* lldpRemOrgDefInfoSubtype */
  { 1, 0x7fffffff } /* lldpRemOrgDefInfoIndex */
};

static snmp_err_t lldpremorgdefinfotable_get_instance(const u32_t *column, const u32_t *row_oid, u8_t row_oid_len, struct snmp_node_instance *cell_instance)
{
  struct netif *netif;
  u32_t TimeMark;
  u32_t lldp_port_id;
  u32_t RemIndex;
  u8_t RemOrgDefInfoOUI[LWIP_LLDP_OUI_LEN];
  u8_t RemOrgDefInfoSubtype;
  u32_t RemOrgDefInfoIndex;
  u8_t byIndex;
  u8_t i;

  LWIP_UNUSED_ARG(column);

  /* check if incoming OID length and if values are in plausible range */
  if (!snmp_oid_in_range(row_oid, row_oid_len, lldpremorgdefinfo_Table_oid_ranges, LWIP_ARRAYSIZE(lldpremorgdefinfo_Table_oid_ranges))) {
    return SNMP_ERR_NOSUCHINSTANCE;
  }

  /* get netif lldp port identifier from incoming OID */
  TimeMark = row_oid[0];
  lldp_port_id = row_oid[1];
  RemIndex = row_oid[2];
  RemOrgDefInfoOUI[0] = (u8_t)row_oid[3];
  RemOrgDefInfoOUI[1] = (u8_t)row_oid[4];
  RemOrgDefInfoOUI[2] = (u8_t)row_oid[5];
  RemOrgDefInfoSubtype = (u8_t)row_oid[6];
  RemOrgDefInfoIndex = row_oid[7];

  NETIF_FOREACH(netif) {
    if (netif->lldp_port_id != 0) {
      if (netif->lldp_port_id == lldp_port_id) {
        memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
        if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
          LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
        }
        for (byIndex = 0; byIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS; byIndex++) {
          if (glldp_agent.rx.remote_system_mib_used[byIndex] == false) {
            continue;
          } else {
            if (glldp_agent.rx.rem_time_mark[byIndex] == TimeMark) {
              if ((u32_t)(byIndex + 1) == RemIndex) {
                for (i = 0; i < LWIP_LLDP_SUPPORT_RX_MAX_ORG_DEF_INFO; i++) {
                  if (memcmp((void *)&glldp_agent.rx.remote_system_mib[byIndex].rcv_org_def[i].oui[0], (void *)&RemOrgDefInfoOUI[0], LWIP_LLDP_OUI_LEN) == 0) {
                    if (glldp_agent.rx.remote_system_mib[byIndex].rcv_org_def[i].org_sub == RemOrgDefInfoSubtype) {
                      if ((u32_t)(i + 1) == RemOrgDefInfoIndex) {
                        /* store netif pointer for subsequent operations (get/test/set) */
                        cell_instance->reference.ptr = netif;
                        return SNMP_ERR_NOERROR;
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;
}
static snmp_err_t lldpremorgdefinfotable_get_next_instance(const u32_t *column, struct snmp_obj_id *row_oid, struct snmp_node_instance *cell_instance)
{
  struct netif *netif;
  u8_t byIndex;
  struct snmp_next_oid_state state;
  u32_t result_temp[LWIP_ARRAYSIZE(lldpremorgdefinfo_Table_oid_ranges)];
  u8_t oui_zero[LWIP_LLDP_OUI_LEN] = {0};
  u8_t i;

  LWIP_UNUSED_ARG(column);

  /* init struct to search next oid */
  snmp_next_oid_init(&state, row_oid->id, row_oid->len, result_temp, LWIP_ARRAYSIZE(lldpremorgdefinfo_Table_oid_ranges));

  /* iterate over all possible OIDs to find the next one */
  NETIF_FOREACH(netif) {
    if (netif->lldp_port_id != 0) {
      memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
      if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
        LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
      }
      for (byIndex = 0; byIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS; byIndex++) {
        if (glldp_agent.rx.remote_system_mib_used[byIndex] == false) {
          continue;
        } else {
          for (i = 0; i < LWIP_LLDP_SUPPORT_RX_MAX_ORG_DEF_INFO; i++) {
            if (memcmp((void *)&glldp_agent.rx.remote_system_mib[byIndex].rcv_org_def[i].oui[0], (void *)&oui_zero[0], LWIP_LLDP_OUI_LEN) != 0) {
              if (glldp_agent.rx.remote_system_mib[byIndex].rcv_org_def[i].org_sub != 0) {
                u32_t test_oid[LWIP_ARRAYSIZE(lldpremorgdefinfo_Table_oid_ranges)];

                test_oid[0] = glldp_agent.rx.rem_time_mark[byIndex];
                test_oid[1] = netif->lldp_port_id;
                test_oid[2] = byIndex + 1;
                test_oid[3] = (u32_t)glldp_agent.rx.remote_system_mib[byIndex].rcv_org_def[i].oui[0];
                test_oid[4] = (u32_t)glldp_agent.rx.remote_system_mib[byIndex].rcv_org_def[i].oui[1];
                test_oid[5] = (u32_t)glldp_agent.rx.remote_system_mib[byIndex].rcv_org_def[i].oui[2];
                test_oid[6] = (u32_t)glldp_agent.rx.remote_system_mib[byIndex].rcv_org_def[i].org_sub;
                test_oid[7] = i + 1;

                /* check generated OID: is it a candidate for the next one? */
                snmp_next_oid_check(&state, test_oid, LWIP_ARRAYSIZE(lldpremorgdefinfo_Table_oid_ranges), netif);
              }
            }
          }
        }
      }
    }
  }

  /* did we find a next one? */
  if (state.status == SNMP_NEXT_OID_STATUS_SUCCESS) {
    snmp_oid_assign(row_oid, state.next_oid, state.next_oid_len);
    /* store netif pointer for subsequent operations (get/test/set) */
    cell_instance->reference.ptr = /* (struct netif*) */state.reference;
    return SNMP_ERR_NOERROR;
  }

  /* not found */
  return SNMP_ERR_NOSUCHINSTANCE;;
}
static s16_t lldpremorgdefinfotable_get_value(struct snmp_node_instance *cell_instance, void *value)
{
  struct netif *netif = (struct netif *)cell_instance->reference.ptr;
  s16_t value_len = 0;
  u32_t RemIndex;
  u32_t RemOrgDefInfoIndex;
  u8_t oui_zero[LWIP_LLDP_OUI_LEN] = {0};

  memset((void *)&glldp_agent, 0, sizeof(LWIP_LLDP_AGENT_VARIABLES));
  if (LWIP_LLDP_mib_get_request(netif->lldp_port_id) == 0) {
    LWIP_LLDP_mib_get_response(netif->lldp_port_id, &glldp_agent);
  }

  switch (SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id))
  {
  case 4:
    {
      /* lldpRemOrgDefInfo */
      RemIndex = cell_instance->instance_oid.id[4] - 1;
      RemOrgDefInfoIndex = cell_instance->instance_oid.id[9] - 1;
      if (RemIndex < LWIP_LLDP_SUPPORT_RX_MAX_NEIGHBORS) {
        if (RemOrgDefInfoIndex < LWIP_LLDP_SUPPORT_RX_MAX_ORG_DEF_INFO) {
          if (memcmp((void *)&glldp_agent.rx.remote_system_mib[RemIndex].rcv_org_def[RemOrgDefInfoIndex].oui[0], (void *)&oui_zero[0], LWIP_LLDP_OUI_LEN) != 0) {
            if (glldp_agent.rx.remote_system_mib[RemIndex].rcv_org_def[RemOrgDefInfoIndex].org_sub != 0) {
              value_len = (s16_t)glldp_agent.rx.remote_system_mib[RemIndex].rcv_org_def[RemOrgDefInfoIndex].org_info_len;
              MEMCPY((void *)value, (void *)glldp_agent.rx.remote_system_mib[RemIndex].rcv_org_def[RemOrgDefInfoIndex].org_info, (size_t)value_len);
            }
          }
        }
      } else {
        value_len = 0;
      }
    }
    break;
  default:
    {
      LWIP_DEBUGF(SNMP_MIB_DEBUG,("lldpremorgdefinfotable_get_value(): unknown id: %"S32_F"\n", SNMP_TABLE_GET_COLUMN_FROM_OID(cell_instance->instance_oid.id)));
      value_len = 0;
    }
    break;
  }
  return value_len;
}
/* --- lldpObjects 1.0.8802.1.1.2.1 ----------------------------------------------------- */
/* --- lldpMIB  ----------------------------------------------------- */
#endif /* LWIP_SNMP && LWIP_LLDP */
